<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>CurveMeshIntersection</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nMesh Methods\nCurveMeshIntersection");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"mesh_methods.htm\">Mesh Methods<\/a> > CurveMeshIntersection<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>CurveMeshIntersection</h1>
<p>Calculates the intersection of a curve object and a mesh object.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.CurveMeshIntersection (strCurve, strMesh [, blnReturnFaces])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.679%;" />
<col style="width: 90.321%;" />
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">strCurve</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;String. &#160;The identifier of the curve to intersect.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">strMesh</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;String. &#160;The identifier of the mesh to intersect.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">blnReturnFaces</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Boolean. &#160;Return both intersection points and face indices. &#160;If omitted or False, then just the intersection points are returned.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.847%;" />
<col style="width: 90.153%;" />
<tr valign="top">
<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Array</p>
</td>
<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If <span style="font-style: italic;"><i>blnReturnFaces</i></span> is either omitted or False, then an array intersection points, if successful.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Array</p>
</td>
<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If <span style="font-style: italic;"><i>blnReturnFaces</i></span> is True, then a one-dimensional array containing information about each intersection if successful. &#160;Each array element is a one-dimensional array that contains the following two elements:</p>
<table cellspacing="0" width="100%">
<col style="width: 5.436%;" />
<col style="width: 8.785%;" />
<col style="width: 85.849%;" />
<tr valign="top">
<td style="width: 5.436%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-weight: bold;">Element</p>
</td>
<td style="width: 8.785%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-weight: bold;">Type</p>
</td>
<td style="width: 85.849%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-weight: bold;">Description</p>
</td>
</tr>
<tr valign="top">
<td style="width: 5.436%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">0</p>
</td>
<td style="width: 8.785%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Array</p>
</td>
<td style="width: 85.849%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">The 3-D intersection point.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 5.436%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">1</p>
</td>
<td style="width: 8.785%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Number</p>
</td>
<td style="width: 85.849%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">The mesh face index on which the intersection point lies.</p>
</td>
</tr>
</table>
</td>
</tr>
<tr valign="top">
<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Null</p>
</td>
<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Const rhCurve = 4</p>
<p class="Code" style="margin-left: 12px;">Const rhMesh = 32</p>
<p class="Code" style="margin-left: 12px;">Dim strCurve, strMesh, arrCMX, arrEv</p>
<p class="Code" style="margin-left: 12px;">strCurve = Rhino.GetObject("Select curve to intersect", rhCurve)</p>
<p class="Code" style="margin-left: 12px;">If Not IsNull(strCurve) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;strMesh = Rhino.GetObject("Select mesh to intersect", rhMesh)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If Not IsNull(strMesh) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;arrCMX = Rhino.CurveMeshIntersection(strCurve, strMesh, True)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;If IsArray(arrCMX) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;For Each arrEv In arrCMX</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;Rhino.Print Rhino.Pt2Str(arrEv(0)) &amp; ", Face index = " &amp; CStr(arrEv(1))</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;Rhino.AddPoint arrEv(0)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;Next</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;End If</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;End If</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3>Also See</h3>
<p><a href="meshclosestpoint.htm">MeshClosestPoint</a></p>
<p><a href="meshmeshintersection.htm">MeshMeshIntersection</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
