<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>MeshContourPoints</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nMesh Methods\nMeshContourPoints");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"mesh_methods.htm\">Mesh Methods<\/a> > MeshContourPoints<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>MeshContourPoints</h1>
<p>Returns the vertices of the polyline curves generated by contouring 
 a mesh object.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.MeshContourPoints (strObject, arrStartPoint, arrEndPoint 
 [,dblInterval ,[ blnRemoveCoincidentPoints]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.408%;" />
	<col style="width: 90.592%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strObject</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;String. &#160;The identifier 
		 of a mesh object.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrStartPoint</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The 3-D starting 
		 point of a center line.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrEndPoint</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The 3-D ending 
		 point of a center line.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblInterval</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Number. &#160;The distance 
		 between contour curves. &#160;If omitted, the interval will be 
		 equal to the diagonal distance of the object's bounding box divided 
		 by 50.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnRemoveCoincidentPoints</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Boolean. &#160;Remove coincident 
		 points. &#160;If True, and the polyline curves from which the 
		 contour point are taken are closed, then duplicate starting and 
		 ending points of the polyline curve will not be returned. The 
		 default is to return duplicate starting and ending points (False).</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 16.344%;" />
	<col style="width: 83.657%;" />
	<tr style="vertical-align: top;">
		<td style="width: 16.344%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Array</p></td>
		<td style="width: 83.657%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">An array of 3-D point arrays, one for each 
		 contour, if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 16.344%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 83.657%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Const rhObjectMesh = 32</p>
<p class="Code" style="margin-left: 12px;">Dim strObject, arrStartPoint, 
 arrEndPoint, arrContours, arrPoints</p>
<p class="Code" style="margin-left: 12px;">strObject = Rhino.GetObject(&quot;Select 
 mesh&quot;, rhObjectMesh )</p>
<p class="Code" style="margin-left: 12px;">arrStartPoint = Rhino.GetPoint(&quot;Base 
 point of center line&quot;)</p>
<p class="Code" style="margin-left: 12px;">arrEndPoint = Rhino.GetPoint(&quot;Endpoint 
 of center line&quot;, arrStartPoint)</p>
<p class="Code" style="margin-left: 12px;">arrContours = Rhino.MeshContourPoints(strObject, 
 arrStartPoint, arrEndPoint)</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrContours) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;For Each arrPoints 
 in arrContours</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;Rhino.AddPointCloud 
 arrPoints</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Next</p>
<p class="Code" style="margin-left: 12px;"><span style="margin-left: 24px;">End 
 If</span></p>
<h3 class="Code">Also See</h3>
<p><a href="../surface_and_polysurface_methods/addsrfcontourcrvs.htm">AddSrfContourCrvs</a></p>
<p><a href="../curve_methods/curvecontourpoints.htm">CurveContourPoints</a></p>
<p><a href="../surface_and_polysurface_methods/surfacecontourpoints.htm">SurfaceContourPoints</a></p>
<p>&#160;</p>
<p>&#160;</p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
