<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddCutPlane</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddCutPlane");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddCutPlane<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddCutPlane</h1>
<p>Adds a planar surface through objects at a designated location. &#160;For 
 more information, see the Rhino help file for the <span style="font-weight: bold;"><b>CutPlane</b></span> 
 command.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddCutPlane (arrObjects, arrStartPoint, arrEndPoint 
 [, arrNormal])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.679%;" />
	<col style="width: 90.321%;" />
	<tr style="height: 24px;" valign="top">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrObjects</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The identifiers 
		 of objects that the cutting planes will pass through.</p></td>
	</tr>
	<tr style="height: 24px;" valign="top">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrStartPoint</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The start 
		 of the line that defines the cutting plane.</p></td>
	</tr>
	<tr style="height: 24px;" valign="top">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrEndPoint</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The end of 
		 the line that defines the cutting plane.</p></td>
	</tr>
	<tr style="height: 24px;" valign="top">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrNormal</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;A vector that will be contained 
		 in the returned planar surface. &#160;In the case of Rhino's <span 
		 style="font-weight: bold;"><b>CutPlane</b></span> command, this is the 
		 normal to, or Z axis of, the active view's construction plane. 
		 &#160;If omitted, the world Z axis is used.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.522%;" />
	<col style="width: 90.478%;" />
	<tr valign="top">
		<td style="width: 9.522%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">String</p></td>
		<td style="width: 90.478%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">The identifier of the new object if successful.</p></td>
	</tr>
	<tr valign="top">
		<td style="width: 9.522%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.478%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim arrObjects, arrPt0, arrPt1</p>
<p class="Code" style="margin-left: 12px;">arrObjects = Rhino.getobjects(&quot;Select 
 objects for cut plane&quot;)</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrObjects) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrPt0 = Rhino.GetPoint(&quot;Start 
 of cut plane&quot;)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsArray(arrPt0) 
 Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;arrPt1 
 = Rhino.GetPoint(&quot;End of cut plane&quot;, arrPt0)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;If IsArray(arrPt1) 
 Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;Rhino.AddCutPlane 
 arrObjects, arrPt0, arrPt1</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;End 
 If</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;End If</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3>Also See</h3>
<p><a href="addplanesurface.htm">AddPlaneSurface</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
