<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddCylinder</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddCylinder");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddCylinder<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddCylinder</h1>
<p>Adds a cylinder to the document.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddCylinder (arrBase, arrHeight, dblRadius [, blnCap 
 [, blnExtrusion]])</p>
<p class="Code">Rhino.AddCylinder (arrPlane, dblHeight, dblRadius [, blnCap 
 [, blnExtrusion]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.679%;" />
	<col style="width: 90.321%;" />
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrBase</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The 3-D base 
		 point of the cylinder.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrPlane</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The base plane 
		 of the cylinder.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrHeight</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The 3-D height 
		 point of the cylinder. &#160;The height point defines the height 
		 and direction of the cylinder.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblHeight</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The height 
		 of the cylinder.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblRadius</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The radius 
		 of the cylinder.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnCap</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Boolean. &#160;Cap the 
		 ends of the cylinder. &#160;If omitted, the ends of the cylinder 
		 will be capped (True).</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: normal;">blnExtrusion</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Boolean. &#160;Create a 
		 lightweight extrusion. The default is to create a surface (uncapped) 
		 or a polysurface (capped) (False).</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.847%;" />
	<col style="width: 90.153%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">String</p></td>
		<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">The identifier of the new object if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim arrBase, arrHeight, dblRadius</p>
<p class="Code" style="margin-left: 12px;">dblRadius = 5.0</p>
<p class="Code" style="margin-left: 12px;">arrBase = Rhino.GetPoint(&quot;Base 
 of cylinder&quot;)</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrBase) Then</p>
<p class="Code" style="margin-left: 24px;">arrHeight = Rhino.GetPoint(&quot;Height 
 of cylinder&quot;, arrBase)</p>
<p class="Code" style="margin-left: 24px;">If IsArray(arrHeight) Then</p>
<p class="Code" style="margin-left: 36px;">Rhino.AddCylinder arrBase, arrHeight, 
 dblRadius</p>
<p class="Code" style="margin-left: 24px;">End If</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3>Also See</h3>
<p><a href="addbox.htm">AddBox</a></p>
<p><a href="addcone.htm">AddCone</a></p>
<p><a href="addsphere.htm">AddSphere</a></p>
<p><a href="addtorus.htm">AddTorus</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
