<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddExtrusion</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddExtrusion");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddExtrusion<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddExtrusion</h1>
<p>Adds a lightweight extrusion object to the document. Lightweight extrusion 
 objects use less memory, mesh faster, and save smaller than the traditional 
 polysurfaces. For more information on lightweight extrusions, see the 
 Rhino help file.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddExtrusion (strCurve, dblHeight, [, blnCap [, arrPlane]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.679%;" />
	<col style="width: 90.321%;" />
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strCurve</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;String. &#160;The identifier 
		 of an existing curve object.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblHeight</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The height 
		 of the extrusion. &#160;If height &gt; 0, the bottom of the extrusion 
		 will be in plane and the top will be height units above the plane. 
		 If height &lt; 0, the top of the extrusion will be in plane and 
		 the bottom will be height units below the plane.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnCap </p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Boolean. &#160;If the curve 
		 is closed and <span style="font-style: italic;"><i>blnCap </i></span>is 
		 true, then the resulting extrusion is capped. &#160;The default 
		 is not to cap (False).</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrPlane</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Array. &#160;The extrusion 
		 plane. If omitted and <span style="font-style: italic;"><i>strCurve</i></span> 
		 is a planar curve, then the curve's plane is used as the extrusion 
		 plane. &#160;If specified, <span style="font-style: italic;"><i>strCurve</i></span> 
		 will be projected to this plane and the results used as the profile 
		 curve.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.847%;" />
	<col style="width: 90.153%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">String</p></td>
		<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">The identifier of the new object if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim strCurve</p>
<p class="Code" style="margin-left: 12px;">strCurve = Rhino.AddCircle(Array(0,0,0), 
 5.0)</p>
<p class="Code" style="margin-left: 12px;">Call Rhino.AddExtrusion(strCurve, 
 10.0, True)</p>
<h3>Also See</h3>
<p><a href="addbox.htm">AddBox</a></p>
<p><a href="addcylinder.htm">AddCylinder</a></p>
<p><a href="addsphere.htm">AddSphere</a></p>
<p><a href="addtorus.htm">AddTorus</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
