<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddNurbsSurface</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddNurbsSurface");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddNurbsSurface<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddNurbsSurface</h1>
<p>Adds a NURBS surface object to the document.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddNurbsSurface (arrPointCount, arrPoints, arrKnotU, 
 arrKnotV, arrDegree [, arrWeights])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 8.991%;" />
	<col style="width: 91.009%;" />
	<tr style="vertical-align: top;">
		<td style="width: 8.991%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrPointCount</p></td>
		<td style="width: 91.009%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The number 
		 of control points in the U and V directions.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.991%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrPoints</p></td>
		<td style="width: 91.009%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;An array of 
		 3-D control points.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.991%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrKnotsU</p></td>
		<td style="width: 91.009%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The knot values 
		 for the surface in the U direction. &#160;The array must contain 
		 <span style="font-style: italic;"><i>arrPointCount(0)</i></span> + <span 
		 style="font-style: italic;"><i>arrDegree(0)</i></span> - 1 elements.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.991%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrKnotsV</p></td>
		<td style="width: 91.009%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The knot values 
		 for the surface in the V direction. &#160;The array must contain 
		 <span style="font-style: italic;"><i>arrPointCount(1)</i></span> + <span 
		 style="font-style: italic;"><i>arrDegree(1)</i></span> - 1 elements.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.991%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrDegree</p></td>
		<td style="width: 91.009%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The degree 
		 of the surface in the U and V directions. &#160;The degree in 
		 each direction must be greater than or equal to one (1).</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.991%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrWeights</p></td>
		<td style="width: 91.009%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The weight 
		 values for the surface. &#160;The number of elements in <span 
		 style="font-style: italic;"><i>arrWeights</i></span> equal the number 
		 of elements in <span style="font-style: italic;"><i>arrPoints</i></span>. 
		 &#160;Weight values must be greater than zero (0).</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.653%;" />
	<col style="width: 90.347%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.653%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">String</p></td>
		<td style="width: 90.347%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">The identifier of the new object if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.653%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.347%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Const rhObjectSurface = 8</p>
<p class="Code" style="margin-left: 12px;">Dim strObject, arrPointCount, 
 arrPoints, arrKnots, arrDegree, arrWeights</p>
<p class="Code" style="margin-left: 12px;">strObject = Rhino.GetObject(&quot;Pick 
 a surface&quot;, rhObjectSurface)</p>
<p class="Code" style="margin-left: 12px;">If Not IsNull(strObject) Then</p>
<p class="Code" style="margin-left: 24px;">arrPointCount = Rhino.SurfacePointCount(strObject)</p>
<p class="Code" style="margin-left: 24px;">arrPoints = Rhino.SurfacePoints(strObject)</p>
<p class="Code" style="margin-left: 24px;">arrKnots = Rhino.SurfaceKnots(strObject)</p>
<p class="Code" style="margin-left: 24px;">arrDegree = Rhino.SurfaceDegree(strObject)</p>
<p class="Code" style="margin-left: 24px;">If Rhino.IsSurfaceRational(strObject) 
 Then</p>
<p class="Code" style="margin-left: 36px;">arrWeights = Rhino.SurfaceWeights(strObject)</p>
<p class="Code" style="margin-left: 36px;">strObject = Rhino.AddNurbsSurface(arrPointCount, 
 arrPoints, arrKnots(0), arrKnots(1), arrDegree, arrWeights)</p>
<p class="Code" style="margin-left: 24px;">Else</p>
<p class="Code" style="margin-left: 36px;">strObject = Rhino.AddNurbsSurface(arrPointCount, 
 arrPoints, arrKnots(0), arrKnots(1), arrDegree)</p>
<p class="Code" style="margin-left: 24px;">End If</p>
<p class="Code" style="margin-left: 24px;">If Not IsNull(strObject) Then 
 Rhino.SelectObject(strObject)</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3>Also See</h3>
<p><a href="issurfacerational.htm">IsSurfaceRational</a></p>
<p><a href="surfacedegree.htm">SurfaceDegree</a></p>
<p><a href="surfaceknotcount.htm">SurfaceKnotCount</a></p>
<p><a href="surfaceknots.htm">SurfaceKnots</a></p>
<p><a href="surfacepointcount.htm">SurfacePointCount</a></p>
<p><a href="surfacepoints.htm">SurfacePoints</a></p>
<p><a href="surfaceweights.htm">SurfaceWeights</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
