<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddPipe</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddPipe");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddPipe<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddPipe</h1>
<p>Creates a singled-walled surface with a circular profile around a curve.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddPipe (strCurve, arrParameters, arrRadii [, intType 
 [, intCap [, blnFit]]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 12.563%;" />
	<col style="width: 87.437%;" />
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">strCurve</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Required. 
		 &#160;String. &#160;The identifier of the path curve object.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">arrParameters</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Required. 
		 &#160;Array. &#160;An array of one or more curve parameters where 
		 changes in radius occur.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">arrRadii </p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Required. 
		 &#160;Array. &#160;An array of radii; one at each curve parameter 
		 in <span style="font-style: italic;"><i>arrParameters</i></span>.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">intType </p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;Number. &#160;The type of shape blending, where:</p>
		<table cellspacing="0" width="100%">
			<col style="width: 11.543%;" />
			<col style="width: 88.457%;" />
			<tr style="vertical-align: top;">
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Value</p></td>
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Description</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">0 (Default)</p></td>
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Local. &#160;The pipe radius stays 
				 constant at the ends and changes more rapidly in the middle.</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">1</p></td>
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Global. &#160;The radius is linearly 
				 blended from one end to the other, creating pipes that 
				 taper from one radius to the other.</p></td>
			</tr>
		</table></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body"><span 
		 style="font-style: italic;"><i>intCap</i></span> </p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;Number. &#160;The end cap mode, where:</p>
		<table cellspacing="0" width="100%">
			<col style="width: 11.543%;" />
			<col style="width: 88.457%;" />
			<tr style="vertical-align: top;">
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Value</p></td>
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Description</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">0 (Default)</p></td>
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">None.</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">1</p></td>
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Flat. &#160;Capped with a planar 
				 surface.</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">2</p></td>
				<td style="padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Round. &#160;Capped with hemispherical 
				 surface.</p></td>
			</tr>
		</table></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">blnFit</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;Boolean. &#160;If the curve is a polycurve of lines and 
		 arcs, the curve is fit and a single surface is created; otherwise 
		 the result is a polysurface with joined surfaces created from 
		 the polycurve segments. &#160;The default is not to fit (False).</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 12.508%;" />
	<col style="width: 87.492%;" />
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Array</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">The 
		 identifier of the new objects if successful. &#160;If <span style="font-style: italic;"><i>strCurve 
		 </i></span>is a line segment, <span style="font-style: italic;"><i>arrParameters</i></span> 
		 contains two curve parameters, <span style="font-style: italic;"><i>arrRadii 
		 </i></span>contains two identical values, and <span style="font-style: italic;"><i>intCap</i></span> 
		 &#160;is either 0 (None) or 1 (Flat), then an extrusion object 
		 will be returned. Otherwise, a polysurface object will be returned. 
		 &#160;Note, it is possible for more than one object to be returned 
		 (when it is not possible to miter sharp corners, for example).</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Null</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">If 
		 not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim strCurve, arrDomain</p>
<p class="Code" style="margin-left: 12px;">strCurve = Rhino.GetObject(&quot;Select 
 curve to create pipe around&quot;, 4, True)</p>
<p class="Code" style="margin-left: 12px;">If Not IsNull(strCurve) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrDomain = Rhino.CurveDomain(strCurve)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Rhino.AddPipe strCurve, 
 Array(arrDomain(0)), Array(4)</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3>Also See</h3>
<p><a href="addthickpipe.htm">AddThickPipe</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
