<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddRevSrf</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddRevSrf");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddRevSrf<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddRevSrf</h1>
<p>Create a surface by revolving a curve around an axis.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddRevSrf (strCurve, arrAxis [, dblStartAngle [, dblEndAngle]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.679%;" />
<col style="width: 90.321%;" />
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">strProfile</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. String. The identifier of the curve to revolve.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrAxis</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;An array of two 3-D points identifying the start point and end point of the rail revolve axis.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">dblStartAngle</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. Number. The starting angle. If omitted, an angle of 0.0 is used.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">dblEndAngle</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. Number. The ending angle. If omitted, an angle of 360.0 is used.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.653%;" />
<col style="width: 90.347%;" />
<tr valign="top">
<td style="width: 9.653%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">String</p>
</td>
<td style="width: 90.347%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">The identifier of the new object if successful.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.653%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Null</p>
</td>
<td style="width: 90.347%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim strCurve</p>
<p class="Code" style="margin-left: 12px;">strCurve = Rhino.AddLine(Array(5,0,0), Array(10,0,10))</p>
<p class="Code" style="margin-left: 12px;">Rhino.AddRevSrf strCurve, Array(Array(0,0,0), Array(0,0,1))</p>
<h3>Also See</h3>
<p><a href="addrailrevsrf.htm">AddRailRevSrf</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
