<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddSweep2</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddSweep2");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddSweep2<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddSweep2</h1>
<p>Adds a surface created through profile curves that define the surface shape and two curves that define the surface edges. For more details on this method, see the Rhino help file for the <span style="font-weight: bold;"><b>Sweep2</b></span> command.</p>
<p>Note, this method does not perform any curve sorting or direction matching on the input shape curves. This is the responsibility of the script writer.</p>
<p>For best results:</p>
<ul type="disc">
<li class="p">
<p>The shape curves should all be oriented in the same direction.</p>
</li>
<li class="p">
<p>The starting point of each shape curve should either intersect with or be close to the first rail curve.</p>
</li>
<li class="p">
<p>The ending point of each shape curve should either intersect with or be close to the second rail curve.</p>
</li>
<li class="p">
<p>The shape curves should be passed in order, starting with the curve closest to the starting point of the rail.</p>
</li>
</ul>
<h3>Syntax</h3>
<p class="Code">Rhino.AddSweep2 (arrRails, arrShapes [, arrStartPt [, arrEndPt [, blnClosed [, blnSimpleSweep [, blnMaintainHeight [, intSimplify [, vaSimplifyArg]]]]]]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.679%;" />
<col style="width: 90.321%;" />
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrRails</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;String. &#160;An array of strings identifying two rail curves.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrShapes</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;An array of strings identifying one or more shape, or cross section, curves.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrStartPt</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Array. &#160;The 3-D starting point of the surface.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrEndPt</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Array. &#160;The 3-D ending point of the surface.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">blnClosed</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Boolean. &#160;If True, then create a closed surface, continuing the surface past the last curve around to the first curve. This option is only available after you select two cross-section curves. &#160;The default value is False.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">blnSimpleSweep</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Boolean. &#160;If True, then create surfaces using exact input. This option generates simpler surfaces in cases when the curves are perfectly set up. &#160;The default value is False.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">blnMaintainHeight</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Boolean. &#160;By default, shape curves normally scale in both the height and width dimensions. To remove the association between the height scaling from the width scaling, set this value to True. &#160;The default value is False.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">intSimplify</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Integer. &#160;Cross section curve options, where 0 = Do Not Simplify, 1 = Refit, and 2 = Rebuild. The default value is 0 = Do Not Simplify.</p>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">vaSimplifyArg</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Variant. &#160;If <span style="font-style: italic;"><i>intSimplify</i></span> = 1 (Refit), then this argument is a number specifying the refit tolerance. &#160;If <span style="font-style: italic;"><i>intSimplify</i></span> = 2 (Rebuild), then this argument is a number specifying the number of control points to rebuild the shape curves.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 11.324%;" />
<col style="width: 88.676%;" />
<tr valign="top">
<td style="width: 11.324%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Array</p>
</td>
<td style="width: 88.676%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">The identifiers of the new surface objects if successful.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 11.324%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Null</p>
</td>
<td style="width: 88.676%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim arrRails, arrShapes</p>
<p class="Code" style="margin-left: 12px;">arrRails = Rhino.GetObjects("Select two rail curve", 4)</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrRails) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrShapes = Rhino.GetObjects("Select cross-section curves", 4)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsArray(arrShapes) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;Rhino.AddSweep2 arrRails, arrShapes</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;End If</p>
<p class="Code" style="margin-left: 12px;"><span style="margin-left: 12px;">End If</span></p>
<h3>Also See</h3>
<p><a href="addsweep1.htm">AddSweep1</a></p>
<p><a href="../curve_methods/curvedirectionsmatch.htm">CurveDirectionsMatch</a></p>
<p><a href="../curve_methods/reversecurve.htm">ReverseCurve</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
