<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddSrfContourCrvs</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nAddSrfContourCrvs");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > AddSrfContourCrvs<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddSrfContourCrvs</h1>
<p>Adds a spaced series of planar curves resulting from the intersection of a defined cutting planes through a surface or a polysurface. For more information, see the Rhino help file for details on the <span style="font-weight: bold;"><b>Contour</b></span> command.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddSrfContourCrvs (strObject, arrStartPoint, arrEndPoint [, dblInterval])</p>
<p class="Code">Rhino.AddSrfContourCrvs (strObject, arrPlane [, dblInterval])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.408%;" />
<col style="width: 90.592%;" />
<tr valign="top">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">strObject</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;String. &#160;The identifier of a surface or polysurface object.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrStartPoint</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;The 3-D starting point of a center line.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrEndPoint</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;The 3-D ending point of a center line.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrPlane</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;A plane that defines the cutting plane.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">dblInterval</p>
</td>
<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;Number. &#160;The distance between contour curves. &#160;If omitted, the interval will be equal to the diagonal distance of the object's bounding box divided by 50.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.548%;" />
<col style="width: 90.452%;" />
<tr valign="top">
<td style="width: 9.548%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Array</p>
</td>
<td style="width: 90.452%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">An array of strings identifying the newly created contour curves if successful.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.548%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Null</p>
</td>
<td style="width: 90.452%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Const rhObjectSurface = 8</p>
<p class="Code" style="margin-left: 12px;">Const rhObjectPolysurface = 16</p>
<p class="Code" style="margin-left: 12px;">Dim strObject, arrStartPoint, arrEndPoint</p>
<p class="Code" style="margin-left: 12px;">strObject = Rhino.GetObject("Select object", rhObjectSurface + rhObjectPolysurface)</p>
<p class="Code" style="margin-left: 12px;">arrStartPoint = Rhino.GetPoint("Base point of center line")</p>
<p class="Code" style="margin-left: 12px;">arrEndPoint = Rhino.GetPoint("Endpoint of center line", arrStartPoint)</p>
<p class="Code" style="margin-left: 12px;">Rhino.AddSrfContourCrvs strObject, arrStartPoint, arrEndPoint</p>
<h3 class="Code">Also See</h3>
<p><a href="../curve_methods/curvecontourpoints.htm">CurveContourPoints</a></p>
<p><a href="../mesh_methods/meshcontourpoints.htm">MeshContourPoints</a></p>
<p><a href="surfacecontourpoints.htm">SurfaceContourPoints</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
