<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>SurfaceDraftAnglePoint</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nSurface & Polysurface Methods\nSurfaceDraftAnglePoint");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"surface_methods.htm\">Surface & Polysurface Methods<\/a> > SurfaceDraftAnglePoint<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>SurfaceDraftAnglePoint</h1>
<p>Returns the surface draft angle and point at a parameter.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.SurfaceDraftAnglePoint (strObject, arrParameter, 
 dblAngle [, arrDirection [, blnEdge]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.632%;" />
	<col style="width: 90.368%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strObject</p></td>
		<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;String. &#160;The surface 
		 object's identifier.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrParameter 
		 </p></td>
		<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The u,v surface 
		 parameter to evaluate.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblAngle</p></td>
		<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The angle 
		 in degrees to test.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrDirection</p></td>
		<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Array. &#160;The direction 
		 vector. If omitted, world z-axis is used.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnEdge</p></td>
		<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Boolean. &#160;Restricts 
		 the point placement to an edge. The default value is False, or 
		 not to restrict point placement to an edge.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.618%;" />
	<col style="width: 90.382%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.618%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Array</p></td>
		<td style="width: 90.382%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Array containing two elements: (0) the 
		 draft angle point and (1) the angle, if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.618%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.382%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Sub TestSurfaceDraftAnglePoint()</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Const rhSrf = 8</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim pick, srf, srf_pt, 
 srf_t, pt</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;pick = Rhino.GetObjectEx(&quot;Select 
 surface object&quot;, rhSrf)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsArray(pick) 
 Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;srf 
 = pick(0)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;srf_pt 
 = pick(3)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;srf_t 
 = Rhino.SurfaceClosestPoint(srf, srf_pt)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;pt = 
 Rhino.SurfaceDraftAnglePoint(srf, srf_t, 10.0)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;If IsArray(pt) 
 Then Call Rhino.AddPoint(pt(0))</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;End If &#160;&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">End Sub</p>
<h3 class="Code">Also See</h3>
<p><a href="../curve_methods/offsetcurve.htm">OffsetCurve</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
