<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="472" rd="layer_methods/layerids.htm|LayerIds" ct=" LayerIds  Returns the identifiers of all layers in the document. Layer identifiers  can be us ..."/><di ky="473" rd="layer_methods/layerlinetype.htm|LayerLinetype" ct=" LayerLinetype  Returns or changes the linetype of a layer.  Syntax  Rhino.LayerLinetype (st ..."/><di ky="474" rd="layer_methods/layerlocked.htm|LayerLocked" ct=" LayerLocked  Returns or changes the locked mode of a layer. This method should be  use instea ..."/><di ky="475" rd="layer_methods/layermaterialindex.htm|LayerMaterialIndex" ct=" LayerMaterialIndex  Returns or changes the material index of a layer.  A material index  of - ..."/><di ky="476" rd="layer_methods/layermode.htm|LayerMode" ct=" LayerMode  OBSOLETE , use either  LayerLocked   or  LayerVisible  instead.  Returns or chan ..."/><di ky="477" rd="layer_methods/layername.htm|LayerName" ct=" LayerName  Returns the name of a layer given the layer&apos;s identifier.  Syntax  Rhino.LayerNa ..."/><di ky="478" rd="layer_methods/layernames.htm|LayerNames" ct=" LayerNames  Returns the names of all layers in the document. Hierarchial layer names  are ret ..."/><di ky="479" rd="layer_methods/layerorder.htm|LayerOrder" ct=" LayerOrder  Returns the current display order index of a layer as displayed in Rhino&apos;s  Layer ..."/><di ky="480" rd="layer_methods/layerprintcolor.htm|LayerPrintColor" ct=" LayerPrintColor  Returns or changes the print color of a layer. Layer print colors are  repre ..."/><di ky="481" rd="layer_methods/layerprintwidth.htm|LayerPrintWidth" ct=" LayerPrintWidth  Returns or changes the print width of a layer. Print width is specified  in  ..."/><di ky="482" rd="layer_methods/layervisible.htm|LayerVisible" ct=" LayerVisible  Returns or changes the visibility property of a layer. This method should  be u ..."/><di ky="483" rd="layer_methods/matchlayer.htm|MatchLayer" ct=" MatchLayer  Matches the properties, such as color, material, linetype, print color,  and prin ..."/><di ky="484" rd="layer_methods/mergelayer.htm|MergeLayer" ct=" MergeLayer  Merges the contents of a source layer with that of a target layer by  moving the  ..."/><di ky="485" rd="layer_methods/parentlayer.htm|ParentLayer" ct=" ParentLayer  Returns or modifies the parent layer of a layer.  Syntax  Rhino.ParentLayer (s ..."/><di ky="486" rd="layer_methods/purgelayer.htm|PurgeLayer" ct=" PurgeLayer  Removes an existing layer from the document.  Unlike the  DeleteLayer   method, P ..."/><di ky="487" rd="layer_methods/renamelayer.htm|RenameLayer" ct=" RenameLayer  Renames an existing layer.  Syntax  Rhino.RenameLayer (strOldName, strNewName) ..."/><di ky="488" rd="layer_methods/selectedlayers.htm|SelectedLayers" ct=" SelectedLayers  Returns the identifiers of the layers that are currently selected in  Rhino&apos;s ..."/><di ky="489" rd="layer_methods/selectlayers.htm|SelectLayers" ct=" SelectLayers  Selects layers in Rhino&apos;s layer user interface. Note, to deselect all  layers,  ..."/><di ky="490" rd="layer_methods/setlayerusertext.htm|SetLayerUserText" ct=" SetLayerUserText  Sets or removes user text stored on a layer. For more details on User  Text ..."/><di ky="491" rd="layer_state_methods/deletelayerstate.htm|DeleteLayerState" ct=" DeleteLayerState  Removes an existing layer state from the document.  Syntax  Rhino.DeleteL ..."/><di ky="492" rd="layer_state_methods/exportlayerstates.htm|ExportLayerStates" ct=" ExportLayerStates  Exports all layer states to an external file.  Syntax  Rhino.ExportLayer ..."/><di ky="493" rd="layer_state_methods/importlayerstates.htm|ImportLayerStates" ct=" ImportLayerStates  Imports layer states from a previously exported layer state file.  Syntax ..."/><di ky="494" rd="layer_state_methods/islayerstate.htm|IsLayerState" ct=" IsLayerState  Verifies the existence of a layer state in the document.  Syntax  Rhino.IsLay ..."/><di ky="495" rd="layer_state_methods/layer_state_methods.htm|Layer State Methods" ct=" Layer State Methods  Rhino&apos;s  LayerStateManager   command allows you to save the states of la ..."/><di ky="496" rd="layer_state_methods/layerstatecount.htm|LayerStateCount" ct=" LayerStateCount  Returns the number of layer states in the document.  Syntax  Rhino.LayerSt ..."/><di ky="497" rd="layer_state_methods/layerstatenames.htm|LayerStateNames" ct=" LayerStateNames  Returns the names of all layer states in the document.  Syntax  Rhino.Laye ..."/><di ky="498" rd="layer_state_methods/renamelayerstate.htm|RenameLayerState" ct=" RenameLayerState  Renames an existing layer state.  Syntax  Rhino.RenameLayerState (strOldS ..."/><di ky="499" rd="layer_state_methods/restorelayerstate.htm|RestoreLayerState" ct=" RestoreLayerState  Restores a previously saved layer state.  Syntax  Rhino.RestoreLayerStat ..."/><di ky="500" rd="layer_state_methods/savelayerstate.htm|SaveLayerState" ct=" SaveLayerState  Saves the current state of the layers in the document.  Syntax  Rhino.SaveL ..."/><di ky="501" rd="light_methods/adddirectionallight.htm|AddDirectionalLight" ct=" AddDirectionalLight  Adds a new directional light object  to the document.  Syntax  Rhino.A ..."/><di ky="502" rd="light_methods/addlinearlight.htm|AddLinearLight" ct=" AddLinearLight  Adds a new linear light object  to the document.  Syntax  Rhino.AddLinearLi ..."/><di ky="503" rd="light_methods/addpointlight.htm|AddPointLight" ct=" AddPointLight  Adds a new point light object  to the document.  Syntax  Rhino.AddPointLight ..."/><di ky="504" rd="light_methods/addrectangularlight.htm|AddRectangularLight" ct=" AddRectangularLight  Adds a new rectangular light object  to the document.  Syntax  Rhino.A ..."/><di ky="505" rd="light_methods/addspotlight.htm|AddSpotLight" ct=" AddSpotLight  Adds a new spot light object  to the document.  Syntax  Rhino.AddSpotLight (a ..."/><di ky="506" rd="light_methods/enablelight.htm|EnableLight" ct=" EnableLight  Enables or disables a light object.  Syntax  Rhino.EnableLight (strObject [, b ..."/><di ky="507" rd="light_methods/isdirectionallight.htm|IsDirectionalLight" ct=" IsDirectionalLight  Verifies a light object is a directional light.  Syntax  Rhino.IsDirect ..."/><di ky="508" rd="light_methods/islight.htm|IsLight" ct=" IsLight  Verifies an object is a light object.  Syntax  Rhino.IsLight (strObject)  Parame ..."/><di ky="509" rd="light_methods/islightenabled.htm|IsLightEnabled" ct=" IsLightEnabled  Verifies a light object is enabled.  Syntax  Rhino.IsLightEnabled (strObjec ..."/><di ky="510" rd="light_methods/islightreference.htm|IsLightReference" ct=" IsLightReference  Verifies a light object is referenced from another file.  Syntax  Rhino.I ..."/><di ky="511" rd="light_methods/islinearlight.htm|IsLinearLight" ct=" IsLinearLight  Verifies a light object is a linear light.  Syntax  Rhino.IsLinearLight (str ..."/><di ky="512" rd="light_methods/ispointlight.htm|IsPointLight" ct=" IsPointLight  Verifies a light object is a point light.  Syntax  Rhino.IsPointLight (strObj ..."/><di ky="513" rd="light_methods/isrectangularlight.htm|IsRectangularLight" ct=" IsRectangularLight  Verifies a light object is a rectangular light.  Syntax  Rhino.IsRectan ..."/><di ky="514" rd="light_methods/isspotlight.htm|IsSpotLight" ct=" IsSpotLight  Verifies a light object is a spot light.  Syntax  Rhino.IsSpotLight (strObject ..."/><di ky="515" rd="light_methods/light_methods.htm|Light Methods" ct=" Light Methods  The following methods are available for creating, querying or manipulating light ..."/><di ky="516" rd="light_methods/lightcolor.htm|LightColor" ct=" LightColor  Returns or changes the color of a light.  Light colors are represented as RGB color ..."/><di ky="517" rd="light_methods/lightcount.htm|LightCount" ct=" LightCount  Returns the number of light objects in the document.  Syntax  Rhino.LightCount  ..."/><di ky="518" rd="light_methods/lightdirection.htm|LightDirection" ct=" LightDirection  Returns or changes the direction of a light object. This function can be used t ..."/><di ky="519" rd="light_methods/lightlocation.htm|LightLocation" ct=" LightLocation  Returns or changes the location of a light object.  Syntax  Rhino.LightLocat ..."/><di ky="520" rd="light_methods/lightname.htm|LightName" ct=" LightName  Returns or modifies the user-definable name of a light object.  Syntax  Rhino.Li ..."/><di ky="521" rd="light_methods/lightobjects.htm|LightObjects" ct=" LightObjects  Returns the identifier of light objects in the document.  Syntax  Rhino.Light ..."/><di ky="522" rd="light_methods/rectangularlightplane.htm|RectangularLightPlane" ct=" RectangularLightPlane  Returns the plane of a rectangular light object.  Syntax  Rhino.Rect ..."/><di ky="523" rd="light_methods/spotlighthardness.htm|SpotLightHardness" ct=" SpotLightHardness  Returns or changes the hardness of a spot light.  Spotlight hardness control ..."/><di ky="524" rd="light_methods/spotlightradius.htm|SpotLightRadius" ct=" SpotLightRadius  Returns or changes the radius of a spot light.  Syntax  Rhino.SpotLightRad ..."/><di ky="525" rd="light_methods/spotlightshadowintensity.htm|SpotLightShadowIntensity" ct=" SpotLightShadowIntensity  Returns or modifies the shadow intensity of a spot  light.  Synta ..."/><di ky="526" rd="line_and_plane_methods/circlecircleintersection.htm|CircleCircleIntersection" ct=" CircleCircleIntersection  Intersects two coplanar circles.  Syntax  Rhino.CircleCircleInter ..."/><di ky="527" rd="line_and_plane_methods/distancetoplane.htm|DistanceToPlane" ct=" DistanceToPlane  Returns the distance from a 3-D point to a plane.  Syntax  Rhino.DistanceT ..."/><di ky="528" rd="line_and_plane_methods/evaluateplane.htm|EvaluatePlane" ct=" EvaluatePlane  Evaluates a plane at a U,V parameter.  Syntax  Rhino.EvaluatePlane (arrPlane ..."/><di ky="529" rd="line_and_plane_methods/intersectplanes.htm|IntersectPlanes" ct=" IntersectPlanes  Calculates the intersection of three planes.  Syntax  Rhino.IntersectPlane ..."/><di ky="530" rd="line_and_plane_methods/linearcintersection.htm|LineArcIntersection" ct=" LineArcIntersection  Intersect an infinite line and an arc.  Syntax  Rhino.LineArcIntersect ..."/><di ky="531" rd="line_and_plane_methods/linebetweencurves.htm|LineBetweenCurves" ct=" LineBetweenCurves  Finds a line segment between a pair of curves such that the line segment   ..."/></ck>