<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="353" rd="document_methods/worksessionmodelaliases.htm|WorkSessionModelAliases" ct=" WorkSessionModelAliases  Returns the aliases of the models used by the worksession, including  ..."/><di ky="354" rd="document_methods/worksessionmodelcount.htm|WorkSessionModelCount" ct=" WorkSessionModelCount  Returns the number of models in the worksession, including the active  ..."/><di ky="355" rd="document_methods/worksessionmodelnames.htm|WorkSessionModelNames" ct=" WorkSessionModelNames  Returns the paths to the models used by the worksession.  Syntax  Rh ..."/><di ky="356" rd="geometry_methods/addclippingplane.htm|AddClippingPlane" ct=" AddClippingPlane  Creates a clipping plane. A clipping plane is a plane for visibly clipping  ..."/><di ky="357" rd="geometry_methods/addpictureframe.htm|AddPictureFrame" ct=" AddPictureFrame  Creates a picture frame and adds it to the document.  Syntax  Rhino.AddPic ..."/><di ky="358" rd="geometry_methods/addpoint.htm|AddPoint" ct=" AddPoint  Adds a point object to the document.  Syntax  Rhino.AddPoint (arrPoint)  Parame ..."/><di ky="359" rd="geometry_methods/addpointcloud.htm|AddPointCloud" ct=" AddPointCloud  Adds a point cloud object to the document.  Syntax  Rhino.AddPointCloud (arr ..."/><di ky="360" rd="geometry_methods/addpoints.htm|AddPoints" ct=" AddPoints  Adds one or more point objects to the document.  Syntax  Rhino.AddPoints (arrPoi ..."/><di ky="361" rd="geometry_methods/addtext.htm|AddText" ct=" AddText  Adds a text string to the document.  Syntax  Rhino.AddText (strText, arrPoint [, d ..."/><di ky="362" rd="geometry_methods/addtextdot.htm|AddTextDot" ct=" AddTextDot  Adds an annotation text dot to the document.  Syntax  Rhino.AddTextDot (strText ..."/><di ky="363" rd="geometry_methods/boundingbox.htm|BoundingBox" ct=" BoundingBox  Returns either a world axis-aligned or a construction plane axis-aligned  boundi ..."/><di ky="364" rd="geometry_methods/circlefrompoints.htm|CircleFromPoints" ct=" CircleFromPoints  Creates a circle fit through points.  Syntax  Rhino.CircleFromPoints (arr ..."/><di ky="365" rd="geometry_methods/clippingplanedefinition.htm|ClippingPlaneDefinition" ct=" ClippingPlaneDefinition  Returns or modifies the underlying plane of a clipping plane object.  ..."/><di ky="366" rd="geometry_methods/clippingplaneview.htm|ClippingPlaneView" ct=" ClippingPlaneView  Returns or modifies the clip view or views of a clipping plane object.  Sy ..."/><di ky="367" rd="geometry_methods/comparegeometry.htm|CompareGeometry" ct=" CompareGeometry  Compares two objects to determine if they are geometrically identical.  Synt ..."/><di ky="368" rd="geometry_methods/flipclippingplane.htm|FlipClippingPlane" ct=" FlipClippingPlane  Reverses the direction of a clipping plane object.  Syntax  Rhino.FlipCl ..."/><di ky="369" rd="geometry_methods/geometry_methods.htm|Geometry Methods" ct=" Geometry Methods  The following methods are available for creating, querying or manipulating  ..."/><di ky="370" rd="geometry_methods/isclippingplane.htm|IsClippingPlane" ct=" IsClippingPlane  Verifies that an object is a clipping plane object.  Syntax  Rhino.IsClipp ..."/><di ky="371" rd="geometry_methods/isknotvectorclamped.htm|IsKnotVectorClamped" ct=" IsKnotVectorClamped  Verifies that a knot vector is clamped. This method works either curve   ..."/><di ky="372" rd="geometry_methods/isknotvectorperiodic.htm|IsKnotVectorPeriodic" ct=" IsKnotVectorPeriodic  Verifies that a knot vector is periodic. This method works either curve  ..."/><di ky="373" rd="geometry_methods/isknotvectoruniform.htm|IsKnotVectorUniform" ct=" IsKnotVectorUniform  Verifies that a knot vector is uniform. This method works either curve   ..."/><di ky="374" rd="geometry_methods/ispictureframe.htm|IsPictureFrame" ct=" IsPictureFrame  Verifies an object is a picture frame object.  Syntax  Rhino.IsPictureFrame ..."/><di ky="375" rd="geometry_methods/ispoint.htm|IsPoint" ct=" IsPoint  Verifies an object is a point object.  Syntax  Rhino.IsPoint (strObject)  Parame ..."/><di ky="376" rd="geometry_methods/ispointcloud.htm|IsPointCloud" ct=" IsPointCloud  Verifies an object is a point cloud object.  Syntax  Rhino.IsPointCloud (strO ..."/><di ky="377" rd="geometry_methods/istext.htm|IsText" ct=" IsText  Verifies an object is a text object.  Syntax  Rhino.IsText (strObject)  Parameter ..."/><di ky="378" rd="geometry_methods/istextdot.htm|IsTextDot" ct=" IsTextDot  Verifies an object is a text dot object.  Syntax  Rhino.IsTextDot (strObject)  ..."/><di ky="379" rd="geometry_methods/knotvectorhasbezierspans.htm|KnotVectorHasBezierSpans" ct=" KnotVectorHasBezierSpans  Verifies that all knots in a knot vector have multiplicity equal to  ..."/><di ky="380" rd="geometry_methods/knotvectorstyle.htm|KnotVectorStyle" ct=" KnotVectorStyle  Returns the style of a knot vector. This method works either curve or  surfa ..."/><di ky="381" rd="geometry_methods/pointcloudcount.htm|PointCloudCount" ct=" PointCloudCount  Returns the point count of a point cloud object.  Syntax  Rhino.PointCloud ..."/><di ky="382" rd="geometry_methods/pointcloudhashiddenpoints.htm|PointCloudHasHiddenPoints" ct=" PointCloudHasHiddenPoints  Verifies that a point cloud object has hidden points.  Syntax  R ..."/><di ky="383" rd="geometry_methods/pointcloudhaspointcolors.htm|PointCloudHasPointColors" ct=" PointCloudHasPointColors  Verifies that a point cloud object has point colors.  Syntax  Rhi ..."/><di ky="384" rd="geometry_methods/pointcloudhidepoints.htm|PointCloudHidePoints" ct=" PointCloudHidePoints  Returns or modifies the hidden points of a point cloud object.  Note, h ..."/><di ky="385" rd="geometry_methods/pointcloudpointcolors.htm|PointCloudPointColors" ct=" PointCloudPointColors  Returns or modifies the point colors of a point cloud object.  Syntax ..."/><di ky="386" rd="geometry_methods/pointcloudpoints.htm|PointCloudPoints" ct=" PointCloudPoints  Returns the points of a point cloud object.  Syntax  Rhino.PointCloudPoin ..."/><di ky="387" rd="geometry_methods/pointcoordinates.htm|PointCoordinates" ct=" PointCoordinates  Returns or modifies the X, Y, and Z coordinates of a point object.  Syntax ..."/><di ky="388" rd="geometry_methods/textdotfont.htm|TextDotFont" ct=" TextDotFont  Returns or modifies the font used by an annotation text dot object.  Syntax  R ..."/><di ky="389" rd="geometry_methods/textdotheight.htm|TextDotHeight" ct=" TextDotHeight  Returns or modifies the height of an annotation text dot object.  Syntax  Rh ..."/><di ky="390" rd="geometry_methods/textdotpoint.htm|TextDotPoint" ct=" TextDotPoint  Returns or modifies the location, or insertion point, of an annotation  text do ..."/><di ky="391" rd="geometry_methods/textdottext.htm|TextDotText" ct=" TextDotText  Returns or modifies the text string of an annotation text dot object.   Annotati ..."/><di ky="392" rd="geometry_methods/textobjectfont.htm|TextObjectFont" ct=" TextObjectFont  Returns or modifies the font used by text object.  Syntax  Rhino.TextObject ..."/><di ky="393" rd="geometry_methods/textobjectformula.htm|TextObjectFormula" ct=" TextObjectFormula  Returns or modifies the text field, or formula, of a text object. Text  fi ..."/><di ky="394" rd="geometry_methods/textobjectheight.htm|TextObjectHeight" ct=" TextObjectHeight  Returns or modifies the height of a text object.  Syntax  Rhino.TextObjec ..."/><di ky="395" rd="geometry_methods/textobjectjustification.htm|TextObjectJustification" ct=" TextObjectJustification  Returns or modifies the justification of a text object.  Syntax  R ..."/><di ky="396" rd="geometry_methods/textobjectmask.htm|TextObjectMask" ct=" TextObjectMask  Returns or modifies the mask of a text object.  Syntax  Rhino.TextObjectMas ..."/><di ky="397" rd="geometry_methods/textobjectplane.htm|TextObjectPlane" ct=" TextObjectPlane  Returns or modifies the plane used by a text object.  Syntax  Rhino.TextOb ..."/><di ky="398" rd="geometry_methods/textobjectpoint.htm|TextObjectPoint" ct=" TextObjectPoint  Returns or modifies the location of a text object.  Syntax  Rhino.TextObje ..."/><di ky="399" rd="geometry_methods/textobjectstyle.htm|TextObjectStyle" ct=" TextObjectStyle  Returns or modifies the font style of a text object.  Syntax  Rhino.TextOb ..."/><di ky="400" rd="geometry_methods/textobjecttext.htm|TextObjectText" ct=" TextObjectText  Returns or modifies the text string of a text object.  Text objects  can be c ..."/><di ky="401" rd="group_methods/addgroup.htm|AddGroup" ct=" AddGroup  Adds a new empty group to the document.  Syntax  Rhino.AddGroup ([strGroup])  P ..."/><di ky="402" rd="group_methods/addobjectstogroup.htm|AddObjectsToGroup" ct=" AddObjectsToGroup  Adds one or more objects to an existing group. Neither the objects nor the g ..."/><di ky="403" rd="group_methods/addobjecttogroup.htm|AddObjectToGroup" ct=" AddObjectToGroup  Adds a single object to an existing group. Neither the object nor the group c ..."/><di ky="404" rd="group_methods/deletegroup.htm|DeleteGroup" ct=" DeleteGroup  Removes an existing group from the document. Reference groups cannot be removed. D ..."/><di ky="405" rd="group_methods/getgroupusertext.htm|GetGroupUserText" ct=" GetGroupUserText  Returns user text that is stored on a group. For more details on User  Text ..."/><di ky="406" rd="group_methods/group_methods.htm|Group Methods" ct=" Group Methods  The following methods are available for adding, querying or manipulating  grou ..."/><di ky="407" rd="group_methods/groupcount.htm|GroupCount" ct=" GroupCount  Returns the number of groups in the document.  Syntax  Rhino.GroupCount ()  P ..."/><di ky="408" rd="group_methods/groupnames.htm|GroupNames" ct=" GroupNames  Returns the name of all the groups in the document.  Syntax  Rhino.GroupNames ( ..."/><di ky="409" rd="group_methods/hidegroup.htm|HideGroup" ct=" HideGroup  Hides a group of object.  Hidden objects are not visible, cannot be snapped to, and  ..."/><di ky="410" rd="group_methods/isgroup.htm|IsGroup" ct=" IsGroup  Verifies the existence of a group.  Syntax  Rhino.IsGroup (strGroup)  Parameters ..."/><di ky="411" rd="group_methods/isgroupempty.htm|IsGroupEmpty" ct=" IsGroupEmpty  Verifies that an existing group is empty, or contains no object members.  Synta ..."/></ck>