<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="884" rd="sample_scripts/dynamicarray.htm|DynamicArray" ct=" DynamicArray  DynamicArray is a VBScript class for maintaining dynamic arrays of data. That is, ..."/><di ky="885" rd="sample_scripts/exportpoints.htm|ExportPoints" ct=" ExportPoints  The following example demonstrates how to export the coordinates of point and poi ..."/><di ky="886" rd="sample_scripts/formatmessage.htm|FormatMessage" ct=" FormatMessage  The following example functions can be useful when formatting strings of text.  ..."/><di ky="887" rd="sample_scripts/gardenpath.htm|GardenPath" ct=" GardenPath  For those familiar with AutoLISP ® , the programming language of Autodesk&apos;s AutoC ..."/><di ky="888" rd="sample_scripts/getarraydim.htm|GetArrayDim" ct=" GetArrayDim  The following example function demonstrates how to determine the number of dimensi ..."/><di ky="889" rd="sample_scripts/importcurvefromexcel.htm|ImportCurveFromExcel" ct=" ImportCurveFromExcel  The following example demonstrates how to create an interpolated curve fr ..."/><di ky="890" rd="sample_scripts/makenurbscurve.htm|MakeNurbsCurve" ct=" MakeNurbsCurve  The following example demonstrates how to create a NURBS curve with specified d ..."/><di ky="891" rd="sample_scripts/readtextfile.htm|ReadTextFile" ct=" ReadTextFile  The following example demonstrates how to create a text file using the scripting  ..."/><di ky="892" rd="sample_scripts/rgb_helpers.htm|RGB Helpers" ct=" RGB Helpers  The following example functions demonstrate how to extract individual red, green,  ..."/><di ky="893" rd="sample_scripts/rhino_rvb.htm|Rhino.rvb" ct=" Rhino.rvb  Rhino.rvb is a sample RhinoScript file that included with Rhino.  The file conta ..."/><di ky="894" rd="sample_scripts/ringtorus.htm|RingTorus" ct=" RingTorus  The following example demonstrates two different methods for generating a torus-shap ..."/><di ky="895" rd="sample_scripts/sample_scripts.htm|Sample Scripts" ct=" Sample Scripts  Several sample scripts have been include to assist you in getting started  wi ..."/><di ky="896" rd="sample_scripts/saveview.htm|SaveView" ct=" SaveView  The following example demonstrates how to write a scripted version of Rhino 2.0&apos;s Sav ..."/><di ky="897" rd="selection_methods/allobjects.htm|AllObjects" ct=" AllObjects  Returns the identifiers of all objects in the document, including reference  obje ..."/><di ky="898" rd="selection_methods/filterobjects.htm|FilterObjects" ct=" FilterObjects  Filters an array of object identifiers.  Syntax  Rhino.FilterObjects (arrObj ..."/><di ky="899" rd="selection_methods/firstobject.htm|FirstObject" ct=" FirstObject  Returns the identifier of the first object in the document.  The first object in t ..."/><di ky="900" rd="selection_methods/getcurveobject.htm|GetCurveObject" ct=" GetCurveObject  Prompts the user to pick, or select, a single curve object.  Syntax  Rhino. ..."/><di ky="901" rd="selection_methods/getobject.htm|GetObject" ct=" GetObject  Prompts the user to pick, or select, a single object.  Syntax  Rhino.GetObject ( ..."/><di ky="902" rd="selection_methods/getobjectex.htm|GetObjectEx" ct=" GetObjectEx  Prompts the user to pick, or select, a single object.  Syntax  Rhino.GetObject ..."/><di ky="903" rd="selection_methods/getobjects.htm|GetObjects" ct=" GetObjects  Prompts the user to pick or select one or more objects.  Syntax  Rhino.GetObjec ..."/><di ky="904" rd="selection_methods/getobjectsex.htm|GetObjectsEx" ct=" GetObjectsEx  Prompts the user to pick or select one or more objects.  Syntax  Rhino.GetObj ..."/><di ky="905" rd="selection_methods/getpointcoordinates.htm|GetPointCoordinates" ct=" GetPointCoordinates  Prompts the user to pick or select one or more point objects. Unlike  GetO ..."/><di ky="906" rd="selection_methods/getsurfaceobject.htm|GetSurfaceObject" ct=" GetSurfaceObject  Prompts the user to pick, or select, a single surface object.  Syntax  Rh ..."/><di ky="907" rd="selection_methods/hiddenobjects.htm|HiddenObjects" ct=" HiddenObjects  Returns the identifiers of all hidden objects in the document, including  refe ..."/><di ky="908" rd="selection_methods/invertselectedobjects.htm|InvertSelectedObjects" ct=" InvertSelectedObjects  Inverts the current object selection.  The identifiers of the newly sele ..."/><di ky="909" rd="selection_methods/lastcreatedobjects.htm|LastCreatedObjects" ct=" LastCreatedObjects  Returns the identifiers of the objects that were most recently created  o ..."/><di ky="910" rd="selection_methods/lastobject.htm|LastObject" ct=" LastObject  Returns the identifier of the last object in the document.  The last object in the  ..."/><di ky="911" rd="selection_methods/lockedobjects.htm|LockedObjects" ct=" LockedObjects  Returns the identifiers of all locked objects in the document, including  refe ..."/><di ky="912" rd="selection_methods/nextobject.htm|NextObject" ct=" NextObject  Returns the identifier of the next object in the document.  Syntax  Rhino.NextO ..."/><di ky="913" rd="selection_methods/normalobjects.htm|NormalObjects" ct=" NormalObjects  Returns the identifiers of all objects that are neither hidden nor locked  in  ..."/><di ky="914" rd="selection_methods/objectsbycolor.htm|ObjectsByColor" ct=" ObjectsByColor  Returns the identifiers of objects based on the objects&apos; color.  Object  colo ..."/><di ky="915" rd="selection_methods/objectsbygroup.htm|ObjectsByGroup" ct=" ObjectsByGroup  Returns the identifiers of objects based on the objects&apos; group name.  Syntax ..."/><di ky="916" rd="selection_methods/objectsbylayer.htm|ObjectsByLayer" ct=" ObjectsByLayer  Returns the identifiers of objects based on the objects&apos; layer.  Syntax  Rh ..."/><di ky="917" rd="selection_methods/objectsbymaterialindex.htm|ObjectsByMaterialIndex" ct=" ObjectsByMaterialIndex  Returns the identifiers of objects based on the objects&apos; material index ..."/><di ky="918" rd="selection_methods/objectsbymaterialsource.htm|ObjectsByMaterialSource" ct=" ObjectsByMaterialSource  Returns the identifiers of objects based on the objects&apos; material sour ..."/><di ky="919" rd="selection_methods/objectsbyname.htm|ObjectsByName" ct=" ObjectsByName  Returns the identifiers of objects based on the objects&apos; user-assigned  name. ..."/><di ky="920" rd="selection_methods/objectsbyregion.htm|ObjectsByRegion" ct=" ObjectsByRegion  Returns the identifiers of objects based on the objects&apos; geometry type.  Syn ..."/><di ky="921" rd="selection_methods/objectsbytype.htm|ObjectsByType" ct=" ObjectsByType  Returns the identifiers of all objects based on the objects&apos; geometry  type.  ..."/><di ky="922" rd="selection_methods/objectsbyurl.htm|ObjectsByURL" ct=" ObjectsByURL  Returns the identifiers of objects based on the objects&apos; user-assigned  URL.  ..."/><di ky="923" rd="selection_methods/pointpick.htm|PointPick" ct=" PointPick  Picks objects using a point selection.  Syntax  Rhino.PointPick (arrPoint [, str ..."/><di ky="924" rd="selection_methods/prevselectedobjects.htm|PrevSelectedObjects" ct=" PrevSelectedObjects  Returns the identifiers of the previously selected objects.  The operation ..."/><di ky="925" rd="selection_methods/referenceobjects.htm|ReferenceObjects" ct=" ReferenceObjects  Returns the identifiers of all reference objects attached to the document.  A ..."/><di ky="926" rd="selection_methods/selectedobjects.htm|SelectedObjects" ct=" SelectedObjects  Returns the identifiers of all objects that are currently selected.  Syntax ..."/><di ky="927" rd="selection_methods/selection_methods.htm|Selection Methods" ct=" Selection Methods  The following methods are available for selecting and obtaining the  ident ..."/><di ky="928" rd="selection_methods/unselectallobjects.htm|UnselectAllObjects" ct=" UnselectAllObjects  Unselects all objects in the document.  Syntax  Rhino.UnselectAllObject ..."/><di ky="929" rd="selection_methods/unselectedobjects.htm|UnselectedObjects" ct=" UnselectedObjects  Returns the identifiers of all objects that are currently unselected.  Syn ..."/><di ky="930" rd="selection_methods/visibleobjects.htm|VisibleObjects" ct=" VisibleObjects  Returns the identifiers of all objects that are visible in a specified  view. ..."/><di ky="931" rd="selection_methods/windowpick.htm|WindowPick" ct=" WindowPick  Picks objects using either a window or crossing selection.  Syntax  Rhino.Windo ..."/><di ky="932" rd="surface_and_polysurface_methods/addbox.htm|AddBox" ct=" AddBox  Adds a new box-shaped polysurface to the document.  Syntax  Rhino.AddBox (arrCorner ..."/><di ky="933" rd="surface_and_polysurface_methods/addcone.htm|AddCone" ct=" AddCone  Adds a cone-shaped polysurface to the document.  Syntax  Rhino.AddCone (arrBase, a ..."/><di ky="934" rd="surface_and_polysurface_methods/addcutplane.htm|AddCutPlane" ct=" AddCutPlane  Adds a planar surface through objects at a designated location.  For  more infor ..."/><di ky="935" rd="surface_and_polysurface_methods/addcylinder.htm|AddCylinder" ct=" AddCylinder  Adds a cylinder to the document.  Syntax  Rhino.AddCylinder (arrBase, arrHeigh ..."/><di ky="936" rd="surface_and_polysurface_methods/addedgesrf.htm|AddEdgeSrf" ct=" AddEdgeSrf  Creates a surface from 2, 3, or 4 edge curves.  Syntax  Rhino.AddEdgeSrf (arrOb ..."/><di ky="937" rd="surface_and_polysurface_methods/addextrusion.htm|AddExtrusion" ct=" AddExtrusion  Adds a lightweight extrusion object to the document. Lightweight extrusion  obj ..."/><di ky="938" rd="surface_and_polysurface_methods/addloftsrf.htm|AddLoftSrf" ct=" AddLoftSrf  Adds a surface created by lofting curves to the document.  	 This function will ..."/><di ky="939" rd="surface_and_polysurface_methods/addnetworksrf.htm|AddNetworkSrf" ct=" AddNetworkSrf  Creates a surface from a network of crossing curves. Note: All curves  in one  ..."/><di ky="940" rd="surface_and_polysurface_methods/addnetworksrfex.htm|AddNetworkSrfEx" ct=" AddNetworkSrfEx  Creates a surface from a network of crossing curves. Note: All curves  in on ..."/><di ky="941" rd="surface_and_polysurface_methods/addnurbssurface.htm|AddNurbsSurface" ct=" AddNurbsSurface  Adds a NURBS surface object to the document.  Syntax  Rhino.AddNurbsSurfac ..."/></ck>