<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="942" rd="surface_and_polysurface_methods/addpatch.htm|AddPatch" ct=" AddPatch  Fits a surface through curve, point, point cloud, and mesh objects.  Syntax  Rhin ..."/><di ky="943" rd="surface_and_polysurface_methods/addpipe.htm|AddPipe" ct=" AddPipe  Creates a singled-walled surface with a circular profile around a curve.  Syntax  ..."/><di ky="944" rd="surface_and_polysurface_methods/addplanarsrf.htm|AddPlanarSrf" ct=" AddPlanarSrf  Creates one or more surfaces from planar curves.  Syntax  Rhino.AddPlanarSrf  ..."/><di ky="945" rd="surface_and_polysurface_methods/addplanesurface.htm|AddPlaneSurface" ct=" AddPlaneSurface  Creates a plane surface.  Syntax  Rhino.AddPlaneSurface (arrPlane, dblDU,  ..."/><di ky="946" rd="surface_and_polysurface_methods/addrailrevsrf.htm|AddRailRevSrf" ct=" AddRailRevSrf  Create a surface by revolving a profile curve along a rail curve.  Syntax  R ..."/><di ky="947" rd="surface_and_polysurface_methods/addrevsrf.htm|AddRevSrf" ct=" AddRevSrf  Create a surface by revolving a curve around an axis.  Syntax  Rhino.AddRevSrf ( ..."/><di ky="948" rd="surface_and_polysurface_methods/addsphere.htm|AddSphere" ct=" AddSphere  Adds a spherical surface to the document.  Syntax  Rhino.AddSphere (arrCenter, d ..."/><di ky="949" rd="surface_and_polysurface_methods/addsrfcontourcrvs.htm|AddSrfContourCrvs" ct=" AddSrfContourCrvs  Adds a spaced series of planar curves resulting from the intersection of a d ..."/><di ky="950" rd="surface_and_polysurface_methods/addsrfcontrolptgrid.htm|AddSrfControlPtGrid" ct=" AddSrfControlPtGrid  Creates a surface from a grid of control points.  Syntax  Rhino.AddSrf ..."/><di ky="951" rd="surface_and_polysurface_methods/addsrfpt.htm|AddSrfPt" ct=" AddSrfPt  Creates a new surface from either 3 or 4 corner points.  Syntax  Rhino.AddSrfPt ( ..."/><di ky="952" rd="surface_and_polysurface_methods/addsrfptgrid.htm|AddSrfPtGrid" ct=" AddSrfPtGrid  Creates a surface from a grid of points.  Syntax  Rhino.AddSrfPtGrid (arrCoun ..."/><di ky="953" rd="surface_and_polysurface_methods/addsrfsectioncrvs.htm|AddSrfSectionCrvs" ct=" AddSrfSectionCrvs  Adds planar curves resulting from the intersection of a defined cutting plan ..."/><di ky="954" rd="surface_and_polysurface_methods/addsweep1.htm|AddSweep1" ct=" AddSweep1  Adds a surface created through profile curves that define the surface shape and one  ..."/><di ky="955" rd="surface_and_polysurface_methods/addsweep2.htm|AddSweep2" ct=" AddSweep2  Adds a surface created through profile curves that define the surface shape and two  ..."/><di ky="956" rd="surface_and_polysurface_methods/addthickpipe.htm|AddThickPipe" ct=" AddThickPipe  Creates a double-walled surface with a circular profile around a curve.  Syntax ..."/><di ky="957" rd="surface_and_polysurface_methods/addtorus.htm|AddTorus" ct=" AddTorus  Adds a torus-shaped revolved surface to the document.  Syntax  Rhino.AddTorus (ar ..."/><di ky="958" rd="surface_and_polysurface_methods/addtruncatedcone.htm|AddTruncatedCone" ct=" AddTruncatedCone  Adds a truncated cone-shaped polysurface to the document.  Syntax  Rhino. ..."/><di ky="959" rd="surface_and_polysurface_methods/booleandifference.htm|BooleanDifference" ct=" BooleanDifference  Performs a Boolean difference operation on two sets of input surfaces  and ..."/><di ky="960" rd="surface_and_polysurface_methods/booleanintersection.htm|BooleanIntersection" ct=" BooleanIntersection  Performs a Boolean intersection operation on two sets of input surfaces  ..."/><di ky="961" rd="surface_and_polysurface_methods/booleanunion.htm|BooleanUnion" ct=" BooleanUnion  Performs a Boolean union operation on a set of input surfaces and polysurfaces.  ..."/><di ky="962" rd="surface_and_polysurface_methods/boxpoints.htm|BoxPoints" ct=" BoxPoints  Returns the corner points of a polysurface box. Points are returned  in counter-cl ..."/><di ky="963" rd="surface_and_polysurface_methods/brepclosestpoint.htm|BrepClosestPoint" ct=" BrepClosestPoint  Returns the point on a surface or polysurface that is closest to a test  po ..."/><di ky="964" rd="surface_and_polysurface_methods/capplanarholes.htm|CapPlanarHoles" ct=" CapPlanarHoles  Caps planar holes in a surface or polysurface. For more details, see the  Cap   ..."/><di ky="965" rd="surface_and_polysurface_methods/changesurfacedegree.htm|ChangeSurfaceDegree" ct=" ChangeSurfaceDegree  Changes the degree of a surface object.  For more information see  the R ..."/><di ky="966" rd="surface_and_polysurface_methods/convertextrusion.htm|ConvertExtrusion" ct=" ConvertExtrusion  Converts an extrusion object to a surface and polysurface object.  Syntax  ..."/><di ky="967" rd="surface_and_polysurface_methods/convertsurfacetobezier.htm|ConvertSurfaceToBezier" ct=" ConvertSurfaceToBezier  Changes the structure of a NURBS surface to a Bézier surface.  Syntax ..."/><di ky="968" rd="surface_and_polysurface_methods/createsolid.htm|CreateSolid" ct=" CreateSolid  Creates a closed polysurface from surfaces and polysurfaces that bound  a region ..."/><di ky="969" rd="surface_and_polysurface_methods/duplicateedgecurves.htm|DuplicateEdgeCurves" ct=" DuplicateEdgeCurves  Duplicates the edge curves of a surface or polysurface. For more informati ..."/><di ky="970" rd="surface_and_polysurface_methods/duplicatesurfaceborder.htm|DuplicateSurfaceBorder" ct=" DuplicateSurfaceBorder  Creates a curve that duplicates a surface or polysurface border.  Syn ..."/><di ky="971" rd="surface_and_polysurface_methods/evaluatesurface.htm|EvaluateSurface" ct=" EvaluateSurface  Evaluates a surface at a U,V parameter.  Syntax  Rhino.EvaluateSurface (st ..."/><di ky="972" rd="surface_and_polysurface_methods/explodepolysurfaces.htm|ExplodePolysurfaces" ct=" ExplodePolysurfaces  Explodes, or un-joins,  one more polysurface objects.  Polysurfaces will b ..."/><di ky="973" rd="surface_and_polysurface_methods/extendsurface.htm|ExtendSurface" ct=" ExtendSurface  Lengthens an untrimmed surface object by a factor value.  Syntax  Rhino.Exte ..."/><di ky="974" rd="surface_and_polysurface_methods/extractisocurve.htm|ExtractIsoCurve" ct=" ExtractIsoCurve  Extracts isoparametric curves from a surface.  Syntax  Rhino.ExtractIsoCur ..."/><di ky="975" rd="surface_and_polysurface_methods/extractsurface.htm|ExtractSurface" ct=" ExtractSurface  Separates or copies a surface (face) or a copy of a surface from a polysurface. ..."/><di ky="976" rd="surface_and_polysurface_methods/extrudecurve.htm|ExtrudeCurve" ct=" ExtrudeCurve  Creates a surface by extruding a curve along a path curve.  Syntax  Rhino.Ext ..."/><di ky="977" rd="surface_and_polysurface_methods/extrudecurvenormal.htm|ExtrudeCurveNormal" ct=" ExtrudeCurveNormal  Extrudes a curve, that lies on a surface, normal to the surface. This  is ..."/><di ky="978" rd="surface_and_polysurface_methods/extrudecurvepoint.htm|ExtrudeCurvePoint" ct=" ExtrudeCurvePoint  Creates a surface by extruding a curve to a point.  Syntax  Rhino.Extrud ..."/><di ky="979" rd="surface_and_polysurface_methods/extrudecurvestraight.htm|ExtrudeCurveStraight" ct=" ExtrudeCurveStraight  Creates a surface by extruding a curve straight along two points that   ..."/><di ky="980" rd="surface_and_polysurface_methods/extrudecurvetapered.htm|ExtrudeCurveTapered" ct=" ExtrudeCurveTapered  Creates a surface by extruding a curve to a taper. Unlike Lofts and Sweeps ..."/><di ky="981" rd="surface_and_polysurface_methods/extrudesurface.htm|ExtrudeSurface" ct=" ExtrudeSurface  Creates a surface or solid by extruding a straight along a path curve.  Synta ..."/><di ky="982" rd="surface_and_polysurface_methods/filletsurfaces.htm|FilletSurfaces" ct=" FilletSurfaces  Create constant radius rolling ball fillets between two surfaces. Note,  this ..."/><di ky="983" rd="surface_and_polysurface_methods/filletsurfacesex.htm|FilletSurfacesEx" ct=" FilletSurfacesEx  Creates a surface between two surfaces. Unlike  FilletSurfaces ,  this meth ..."/><di ky="984" rd="surface_and_polysurface_methods/fitsurface.htm|FitSurface" ct=" FitSurface  Reduces the number of surface control points while maintaining the surfaces&apos; same g ..."/><di ky="985" rd="surface_and_polysurface_methods/flipsurface.htm|FlipSurface" ct=" FlipSurface  Returns or changes the normal direction of a surface. This feature can also be fou ..."/><di ky="986" rd="surface_and_polysurface_methods/insertsurfaceknot.htm|InsertSurfaceKnot" ct=" InsertSurfaceKnot  Inserts a knot into a surface object.  Syntax  Rhino.InsertSurfaceKnot ( ..."/><di ky="987" rd="surface_and_polysurface_methods/intersectbreps.htm|IntersectBreps" ct=" IntersectBreps  Intersects a surface or polysurface object with another surface or polysurface  ..."/><di ky="988" rd="surface_and_polysurface_methods/intersectspheres.htm|IntersectSpheres" ct=" IntersectSpheres  Calculates the intersection of two spheres.     Syntax  Rhino.IntersectSp ..."/><di ky="989" rd="surface_and_polysurface_methods/isbox.htm|IsBox" ct=" IsBox  Verifies a polysurface object is a box.  Syntax  Rhino.IsBox (strObject)  Paramete ..."/><di ky="990" rd="surface_and_polysurface_methods/isbrep.htm|IsBrep" ct=" IsBrep  Verifies an object is a Brep, or a boundary representation model, object.  Syntax  ..."/><di ky="991" rd="surface_and_polysurface_methods/isbrepmanifold.htm|IsBrepManifold" ct=" IsBrepManifold  Verifies a polysurface object is manifold.  A polysurface for which every edge  ..."/><di ky="992" rd="surface_and_polysurface_methods/iscone.htm|IsCone" ct=" IsCone  Determines if a surface is a portion of a cone.  Syntax  Rhino.IsCone (strSurface [ ..."/><di ky="993" rd="surface_and_polysurface_methods/iscylinder.htm|IsCylinder" ct=" IsCylinder  Determines if a surface is a portion of a cylinder.  Syntax  Rhino.IsCylinder ( ..."/><di ky="994" rd="surface_and_polysurface_methods/isextrusion.htm|IsExtrusion" ct=" IsExtrusion  Verifies that an object is a lightweight extrusion object.  Syntax  Rhino.IsEx ..."/><di ky="995" rd="surface_and_polysurface_methods/isnurbssurface.htm|IsNurbsSurface" ct=" IsNurbsSurface  Verifies an object is a NURBS surface.  Syntax  Rhino.IsNurbsSurface (strOb ..."/><di ky="996" rd="surface_and_polysurface_methods/isparameteronsurface.htm|IsParameterOnSurface" ct=" IsParameterOnSurface  Verifies that a parameter space point is on a trimmed surface, or not on  ..."/></ck>