<?xml version="1.0" encoding="UTF-8"?>
<ck><di ky="118" rd="block_methods/renameblock.htm|RenameBlock" ct=" RenameBlock  Renames an existing block definition.  Syntax  Rhino.RenameBlock (strOldBlock, ..."/><di ky="119" rd="curve_methods/addarc.htm|AddArc" ct=" AddArc  Adds an arc curve to the document.  Syntax  Rhino.AddArc (arrPlane, dblRadius, dblA ..."/><di ky="120" rd="curve_methods/addarcpttanpt.htm|AddArcPtTanPt" ct=" AddArcPtTanPt  Adds an arc curve, created from a start point, a start direction, and  an end  ..."/><di ky="121" rd="curve_methods/addblendcurve.htm|AddBlendCurve" ct=" AddBlendCurve  Makes a curve blend between two curves at the parameters specified with  the d ..."/><di ky="122" rd="curve_methods/addcircle.htm|AddCircle" ct=" AddCircle  Adds a circle curve to the document.  Syntax  Rhino.AddCircle (arrPlane, dblRadi ..."/><di ky="123" rd="curve_methods/addcircle3pt.htm|AddCircle3Pt" ct=" AddCircle3Pt  Adds a 3-point circle curve to the document.  Syntax  Rhino.AddCircle3Pt (arr ..."/><di ky="124" rd="curve_methods/addcirclepttanpt.htm|AddCirclePtTanPt" ct=" AddCirclePtTanPt  Adds a circle curve, created from two points and a start direction,  to the ..."/><di ky="125" rd="curve_methods/addcircletantan.htm|AddCircleTanTan" ct=" AddCircleTanTan  Adds a circle curve that is tangent to 2 curves to the document.  Syntax  ..."/><di ky="126" rd="curve_methods/addcircletantantan.htm|AddCircleTanTanTan" ct=" AddCircleTanTanTan  Adds a circle curve that is tangent to 3 curves to the document.  Syntax ..."/><di ky="127" rd="curve_methods/addcurve.htm|AddCurve" ct=" AddCurve  Adds a control points curve object to the document.  Syntax  Rhino.AddCurve (arrP ..."/><di ky="128" rd="curve_methods/addellipse.htm|AddEllipse" ct=" AddEllipse  Adds an elliptical curve to the document.  Syntax  Rhino.AddEllipse (arrPlane,  ..."/><di ky="129" rd="curve_methods/addellipse3pt.htm|AddEllipse3Pt" ct=" AddEllipse3Pt  Adds a 3 point elliptical curve to the document.  Syntax  Rhino.AddEllipse3P ..."/><di ky="130" rd="curve_methods/addfilletcurve.htm|AddFilletCurve" ct=" AddFilletCurve  Adds a fillet curve between two curve objects.  Syntax  Rhino.AddFilletCurv ..."/><di ky="131" rd="curve_methods/addinterpcrvonsrf.htm|AddInterpCrvOnSrf" ct=" AddInterpCrvOnSrf  Adds an interpolated curve object that lies on a specified surface.  Note, ..."/><di ky="132" rd="curve_methods/addinterpcrvonsrfuv.htm|AddInterpCrvOnSrfUV" ct=" AddInterpCrvOnSrfUV  Adds an interpolated curve object. based on surface parameters, that  li ..."/><di ky="133" rd="curve_methods/addinterpcurve.htm|AddInterpCurve" ct=" AddInterpCurve  Adds an interpolated curve object to  the document.  Options  exist to make a ..."/><di ky="134" rd="curve_methods/addinterpcurveex.htm|AddInterpCurveEx" ct=" AddInterpCurveEx  Adds an interpolated curve object to  the document similar to Rhino&apos;s   Int ..."/><di ky="135" rd="curve_methods/addline.htm|AddLine" ct=" AddLine  Adds a line curve to the current model.  Syntax  Rhino.AddLine (arrStart, arrEnd) ..."/><di ky="136" rd="curve_methods/addnurbscurve.htm|AddNurbsCurve" ct=" AddNurbsCurve  Adds a NURBS curve object to the document.  Syntax  Rhino.AddNurbsCurve (arr ..."/><di ky="137" rd="curve_methods/addpolygon.htm|AddPolygon" ct=" AddPolygon  Adds a regular polygon, either inscribed in or circumscribe about, a  circle to t ..."/><di ky="138" rd="curve_methods/addpolyline.htm|AddPolyline" ct=" AddPolyline  Adds a polyline curve object to the current model.  Syntax  Rhino.AddPolyline  ..."/><di ky="139" rd="curve_methods/addspiral.htm|AddSpiral" ct=" AddSpiral  Adds a spiral or helical curve object to the document.  Syntax  Rhino.AddSpiral  ..."/><di ky="140" rd="curve_methods/addspiral2.htm|AddSpiral2" ct=" AddSpiral2  Adds a spiral or helical curve object to the document.  Syntax  Rhino.AddSpiral ..."/><di ky="141" rd="curve_methods/addstarpolygon.htm|AddStarPolygon" ct=" AddStarPolygon  Adds a regular star polygon to the document.  Vertices alternate  between bei ..."/><di ky="142" rd="curve_methods/addsubcrv.htm|AddSubCrv" ct=" AddSubCrv  Adds a new curve object based on a portion, or interval, of an existing  curve obj ..."/><di ky="143" rd="curve_methods/addtextoutlines.htm|AddTextOutlines" ct=" AddTextOutlines  Adds outline curves created from a text string to the document. The  functio ..."/><di ky="144" rd="curve_methods/arcangle.htm|ArcAngle" ct=" ArcAngle  Returns the angle of an arc curve object.  Syntax  Rhino.ArcAngle (strObject [, i ..."/><di ky="145" rd="curve_methods/arccenterpoint.htm|ArcCenterPoint" ct=" ArcCenterPoint  Returns the center point of an arc curve object.  Syntax  Rhino.ArcCenterPo ..."/><di ky="146" rd="curve_methods/arcmidpoint.htm|ArcMidPoint" ct=" ArcMidPoint  Returns the mid point of an arc curve object.  Syntax  Rhino.ArcMidPoint (strO ..."/><di ky="147" rd="curve_methods/arcradius.htm|ArcRadius" ct=" ArcRadius  Returns the radius of an arc curve object.  Syntax  Rhino.ArcRadius (strObject [ ..."/><di ky="148" rd="curve_methods/changecurvedegree.htm|ChangeCurveDegree" ct=" ChangeCurveDegree  Changes the degree of a curve object. For more information see the Rhino   ..."/><di ky="149" rd="curve_methods/circlecenterpoint.htm|CircleCenterPoint" ct=" CircleCenterPoint  Returns the center point of a circle curve object.  Syntax  Rhino.Circle ..."/><di ky="150" rd="curve_methods/circlecircumference.htm|CircleCircumference" ct=" CircleCircumference  Returns the circumference of a circle curve object.  Syntax  Rhino.Cir ..."/><di ky="151" rd="curve_methods/circleradius.htm|CircleRadius" ct=" CircleRadius  Returns the radius of a circle curve object.  Syntax  Rhino.CircleRadius (str ..."/><di ky="152" rd="curve_methods/cleanuppolycurve.htm|CleanUpPolyCurve" ct=" CleanUpPolyCurve  Clean up polycurve curve object by removing any nesting of polycurves.  Syn ..."/><di ky="153" rd="curve_methods/closecurve.htm|CloseCurve" ct=" CloseCurve  Closes an open curve object by making adjustments to the end points so that they me ..."/><di ky="154" rd="curve_methods/closedcurveorientation.htm|ClosedCurveOrientation" ct=" ClosedCurveOrientation  Determine the orientation (counter-clockwise or clockwise) of a closed, ..."/><di ky="155" rd="curve_methods/convertcurvetobezier.htm|ConvertCurveToBezier" ct=" ConvertCurveToBezier  Changes the structure of a NURBS curve to a Bézier curve.  Syntax  Rh ..."/><di ky="156" rd="curve_methods/convertcurvetopolyline.htm|ConvertCurveToPolyline" ct=" ConvertCurveToPolyline  Converts a curve to a polyline curve.  Syntax  Rhino.ConvertCurveTo ..."/><di ky="157" rd="curve_methods/curve_addarc3pt.htm|AddArc3Pt" ct=" AddArc3Pt  Adds a 3-point arc curve to the document.  Syntax  Rhino.AddArc3Pt (arrStart, ar ..."/><di ky="158" rd="curve_methods/curve_methods.htm|Curve Methods" ct=" Curve Methods  The following methods are available for creating, querying or manipulating  cu ..."/><di ky="159" rd="curve_methods/curvearclengthpoint.htm|CurveArcLengthPoint" ct=" CurveArcLengthPoint  Returns the point on the curve that is a specified arc length from the sta ..."/><di ky="160" rd="curve_methods/curvearea.htm|CurveArea" ct=" CurveArea  Returns that area of closed planar curves. The results are based on  the current d ..."/><di ky="161" rd="curve_methods/curveareacentroid.htm|CurveAreaCentroid" ct=" CurveAreaCentroid  Returns that area centroid of closed, planar curves. The results are  base ..."/><di ky="162" rd="curve_methods/curvearrows.htm|CurveArrows" ct=" CurveArrows  Enables or disabled a curve object&apos;s annotation arrows.  Syntax  Rhino.CurveAr ..."/><di ky="163" rd="curve_methods/curvebooleandifference.htm|CurveBooleanDifference" ct=" CurveBooleanDifference  Calculates the difference between two closed, planar curves and adds  ..."/><di ky="164" rd="curve_methods/curvebooleanintersection.htm|CurveBooleanIntersection" ct=" CurveBooleanIntersection  Calculates the intersection of two closed, planar curves and adds the ..."/><di ky="165" rd="curve_methods/curvebooleanunion.htm|CurveBooleanUnion" ct=" CurveBooleanUnion  Calculates the union of two or more closed, planar curves and adds the  re ..."/><di ky="166" rd="curve_methods/curvebrepintersect.htm|CurveBrepIntersect" ct=" CurveBrepIntersect  Intersects a curve object with a brep object. Note, unlike the  CurveSurfac ..."/><di ky="167" rd="curve_methods/curveclosestobject.htm|CurveClosestObject" ct=" CurveClosestObject  Returns the 3-D point locations on two objects where they are closest  to ..."/><di ky="168" rd="curve_methods/curveclosestpoint.htm|CurveClosestPoint" ct=" CurveClosestPoint  Returns the parameter of the point on a curve that is closest to a test poin ..."/><di ky="169" rd="curve_methods/curvecontourpoints.htm|CurveContourPoints" ct=" CurveContourPoints  Returns the 3-D point locations calculated by contouring a curve object.  ..."/><di ky="170" rd="curve_methods/curvecurvature.htm|CurveCurvature" ct=" CurveCurvature  Returns the curvature of a curve at a parameter.  See the Rhino help file for d ..."/><di ky="171" rd="curve_methods/curvecurveintersection.htm|CurveCurveIntersection" ct=" CurveCurveIntersection  Calculates the intersection of two curve objects.  Syntax  Rhino.Cu ..."/><di ky="172" rd="curve_methods/curvedegree.htm|CurveDegree" ct=" CurveDegree  Returns the degree of a curve object.  Syntax  Rhino.CurveDegree (strObject [, ..."/><di ky="173" rd="curve_methods/curvedeviation.htm|CurveDeviation" ct=" CurveDeviation  Returns the minimum and maximum deviation between two curve objects.  For mor ..."/><di ky="174" rd="curve_methods/curvedim.htm|CurveDim" ct=" CurveDim  Returns the dimension of a curve object.  Syntax  Rhino.CurveDim (strObject [, in ..."/><di ky="175" rd="curve_methods/curvedirectionsmatch.htm|CurveDirectionsMatch" ct=" CurveDirectionsMatch  Tests if two curve objects are generally in the same direction or if they ..."/><di ky="176" rd="curve_methods/curvediscontinuity.htm|CurveDiscontinuity" ct=" CurveDiscontinuity  Search for a derivative, tangent, or curvature discontinuity in a curve   ..."/><di ky="177" rd="curve_methods/curvedomain.htm|CurveDomain" ct=" CurveDomain  Returns the domain of a curve object.  Syntax  Rhino.CurveDomain (strObject [, ..."/></ck>