<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>ProjectPointToSurface</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nPoint & Vector Methods\nProjectPointToSurface");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"point_and_vector_methods.htm\">Point & Vector Methods<\/a> > ProjectPointToSurface<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>ProjectPointToSurface</h1>
<p>Projects one or more points onto one or more surfaces or polysurfaces.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.ProjectPointToSurface (arrPoint, strSurface, arrDirection)</p>
<p class="Code">Rhino.ProjectPointToSurface (arrPoint, arrSurfaces, arrDirection)</p>
<p class="Code">Rhino.ProjectPointToSurface (arrPoints, strSurface, arrDirection)</p>
<p class="Code">Rhino.ProjectPointToSurface (arrPoints, arrSurfaces, arrDirection)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.632%;" />
<col style="width: 90.368%;" />
<tr valign="top">
<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrPoints</p>
</td>
<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;A 3-D point to project.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrPoints</p>
</td>
<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;An array of 3-D points to project.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">strSurface</p>
</td>
<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;String. &#160;The identifier of the surface or polysurface object to project onto.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrSurfaces</p>
</td>
<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;The identifiers of the surface or polysurface objects to project onto.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.632%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrDirection</p>
</td>
<td style="width: 90.368%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;The direction (3-D vector) to project the points.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.618%;" />
<col style="width: 90.382%;" />
<tr valign="top">
<td style="width: 9.618%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Array</p>
</td>
<td style="width: 90.382%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">An array of 3-D points if successful.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.618%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Null</p>
</td>
<td style="width: 90.382%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Sub TestProjectPoints</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim arrObjects, strSurface</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;strSurface = Rhino.GetObject("Select surface to project onto", 8)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrObjects = Rhino.GetObjects("Select points to project", 1)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim nBound, arrPoints</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;nBound = UBound(arrObjects)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;ReDim arrPoints( nBound )</p>
<p class="Code" style="margin-left: 12px;">&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim i &#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;For i = 0 To nBound</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;arrPoints(i) = Rhino.PointCoordinates( arrObjects(i) )</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Next</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;' Project down...</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim arrResults</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrResults = Rhino.ProjectPointToSurface(arrPoints, strSurface, Array(0,0,-1))</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Rhino.AddPoints arrResults</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">End Sub</p>
<h3 class="Code">Also See</h3>
<p><a href="../curve_methods/projectcurvetomesh.htm">ProjectCurveToMesh</a></p>
<p><a href="../curve_methods/projectcurvetosurface.htm">ProjectCurveToSurface</a></p>
<p><a href="projectpointtomesh.htm">ProjectPointToMesh</a></p>
<p>&#160;</p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
