<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>ArrayPointsOnSurface</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("Sample Scripts\nArrayPointsOnSurface");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"sample_scripts.htm\">Sample Scripts<\/a> > ArrayPointsOnSurface<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>ArrayPointsOnSurface</h1>
<p>The following example demonstrates how to array point objects on a surface.</p>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Option Explicit</p>
<p class="CodeComment" style="margin-left: 12px;">'------------------------------------------------------------------------------</p>
<p class="CodeComment" style="margin-left: 12px;">' Subroutine: ArrayPointsOnSurface</p>
<p class="CodeComment" style="margin-left: 12px;">' Purpose: &#160;&#160;&#160;Creates an array of points on a surface.</p>
<p class="CodeComment" style="margin-left: 12px;">'------------------------------------------------------------------------------</p>
<p class="Code" style="margin-left: 12px;">Sub ArrayPointsOnSurface()</p>
<p class="Code" style="margin-left: 24px;">Dim strObject, nRows, nColumns</p>
<p class="Code" style="margin-left: 24px;">Dim U, V, i, j, arrParam(1), arrPoint</p>
<p class="CodeComment" style="margin-left: 24px;">' Get the surface object</p>
<p class="Code" style="margin-left: 24px;">strObject = Rhino.GetObject("Select surface", 8)</p>
<p class="Code" style="margin-left: 24px;">If IsNull(strObject) Then Exit Sub</p>
<p class="CodeComment" style="margin-left: 24px;">' Get the number of rows</p>
<p class="Code" style="margin-left: 24px;">nRows = Rhino.GetInteger("Number of rows", 2, 2)</p>
<p class="Code" style="margin-left: 24px;">If IsNull(nRows) Then Exit Sub</p>
<p class="Code" style="margin-left: 24px;">nRows = nRows - 1</p>
<p class="CodeComment" style="margin-left: 24px;">' Get the number of columns</p>
<p class="Code" style="margin-left: 24px;">nColumns = Rhino.GetInteger("Number of columns", 2, 2)</p>
<p class="Code" style="margin-left: 24px;">If IsNull(nColumns) Then Exit Sub</p>
<p class="Code" style="margin-left: 24px;">nColumns = nColumns - 1</p>
<p class="CodeComment" style="margin-left: 24px;">' Get the domain of the surface</p>
<p class="Code" style="margin-left: 24px;">U = Rhino.SurfaceDomain(strObject, 0)</p>
<p class="Code" style="margin-left: 24px;">V = Rhino.SurfaceDomain(strObject, 1)</p>
<p class="Code" style="margin-left: 24px;">If Not IsArray(U) or Not IsArray(V) Then Exit Sub</p>
<p class="CodeComment" style="margin-left: 24px;">' Add the points</p>
<p class="Code" style="margin-left: 24px;">For i = 0 to nRows</p>
<p class="Code" style="margin-left: 36px;">arrParam(0) = U(0) + (((U(1) - U(0)) / nRows) * i)</p>
<p class="Code" style="margin-left: 36px;">For j = 0 to nColumns</p>
<p class="Code" style="margin-left: 48px;">arrParam(1) = V(0) + (((V(1) - V(0)) / nColumns) * j)</p>
<p class="Code" style="margin-left: 48px;">arrPoint = Rhino.EvaluateSurface(strObject, arrParam)</p>
<p class="Code" style="margin-left: 48px;">If IsArray(arrPoint) Then <span style="margin-left: 60px;">Rhino.AddPoint arrPoint</span></p>
<p class="Code" style="margin-left: 36px;">Next</p>
<p class="Code" style="margin-left: 24px;">Next</p>
<p class="Code" style="margin-left: 12px;">End Sub</p>
<p>&#160;</p>
<p>&#160;</p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
