<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddSubCrv</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nCurve Methods\nAddSubCrv");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"curve_methods.htm\">Curve Methods<\/a> > AddSubCrv<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddSubCrv</h1>
<p>Adds a new curve object based on a portion, or interval, of an existing 
 curve object. This function is similar in operation to Rhino's <span style="font-weight: bold;"><b>SubCrv</b></span> 
 command.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddSubCrv (strObject, dblParam0, dblParam1)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.408%;" />
	<col style="width: 90.592%;" />
	<tr valign="top">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strObject</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;String. &#160;The identifier 
		 of the source curve object.</p></td>
	</tr>
	<tr valign="top">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblParam0</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The first 
		 parameter on the source curve.</p></td>
	</tr>
	<tr valign="top">
		<td style="width: 9.408%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblParam1</p></td>
		<td style="width: 90.592%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The second 
		 parameter on the source curve.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.53%;" />
	<col style="width: 90.47%;" />
	<tr valign="top">
		<td style="width: 9.53%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">String</p></td>
		<td style="width: 90.47%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">The identifier of the new object if successful.</p></td>
	</tr>
	<tr valign="top">
		<td style="width: 9.53%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.47%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim arrCurve, arrPt0, arrPt1, 
 t0, t1</p>
<p class="Code" style="margin-left: 12px;">arrCurve = Rhino.GetCurveObject</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrCurve) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrPt0 = Rhino.GetPointOnCurve(arrCurve(0))</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsArray(arrPt0) 
 Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;arrPt1 
 = Rhino.GetPointOnCurve(arrCurve(0))</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;If IsArray(arrPt1) 
 Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;t0 
 = Rhino.CurveClosestPoint(arrCurve(0), arrPt0)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;t1 
 = Rhino.CurveClosestPoint(arrCurve(0), arrPt1)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;Rhino.AddSubCrv 
 arrCurve(0), t0, t1</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;End 
 If</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;End If</p>
<p class="Code" style="margin-left: 12px;"><span style="margin-left: 12px;">End 
 If</span></p>
<h3>Also See</h3>
<p><a href="curveclosestpoint.htm">CurveClosestPoint</a></p>
<p><a href="../selection_methods/getcurveobject.htm">GetCurveObject</a></p>
<p><a href="../user_interface_methods/getpointoncurve.htm">GetPointOnCurve</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
