<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>CircleFromPoints</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nGeometry Methods\nCircleFromPoints");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"geometry_methods.htm\">Geometry Methods<\/a> > CircleFromPoints<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>CircleFromPoints</h1>
<p>Creates a circle fit through points.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.CircleFromPoints (arrPoints)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.679%;" />
	<col style="width: 90.321%;" />
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrPoints</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;An array of 
		 3-D points. &#160;The array must contain at least three points.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.53%;" />
	<col style="width: 90.47%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.53%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Array</p></td>
		<td style="width: 90.47%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">An array containing the definition of the 
		 circle if successful. &#160;The elements of the array are as follows:</p>
		<table cellspacing="0" width="100%">
			<col style="width: 5.25%;" />
			<col style="width: 8.202%;" />
			<col style="width: 86.548%;" />
			<tr style="vertical-align: top;">
				<td style="width: 5.25%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Element</p></td>
				<td style="width: 8.202%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Type</p></td>
				<td style="width: 86.548%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Description</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="width: 5.25%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">0</p></td>
				<td style="width: 8.202%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Array</p></td>
				<td style="width: 86.548%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">The plane of the circle.</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="width: 5.25%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">1</p></td>
				<td style="width: 8.202%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Number</p></td>
				<td style="width: 86.548%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">The radius of the circle.</p></td>
			</tr>
		</table></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.53%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.47%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim arrPoints, arrCircle</p>
<p class="Code" style="margin-left: 12px;">arrPoints = Rhino.GetPointCoordinates(&quot;Select 
 points&quot;)</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrPoints) Then</p>
<p class="Code" style="margin-left: 24px;">arrCircle = Rhino.CircleFromPoints(arrPoints)</p>
<p class="Code" style="margin-left: 24px;">If IsArray(arrCircle) Then</p>
<p class="Code" style="margin-left: 24px;">&#160;&#160;Rhino.AddCircle 
 arrCircle(0), arrCircle(1)</p>
<p class="Code" style="margin-left: 24px;">End If</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3>Also See</h3>
<p><a href="../curve_methods/addcircle.htm">AddCircle</a></p>
<p><a href="../curve_methods/iscircle.htm">IsCircle</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
