<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>GetLine</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nUser Interface Methods\nGetLine");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"user_interface_methods.htm\">User Interface Methods<\/a> > GetLine<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>GetLine</h1>
<p>Prompts the user to pick points that define a line.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.GetLine ([intMode [, arrPoint [, strMessage1 [, strMessage2 
 [, strMessage3 [, blnBothSides]]]]]])</p>
<h3>Parameters</h3>
<table style="left: 0px; top: 152px;" cellspacing="0" width="100%">
	<col style="width: 12.524%;" />
	<col style="width: 87.476%;" />
	<tr style="vertical-align: top; height: 20px;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">intMode </p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;Integer. &#160;The line definition mode. The possible values 
		 are as follows:</p>
		<table cellspacing="0" width="100%">
			<col style="width: 15.485%;" />
			<col style="width: 84.515%;" />
			<tr>
				<td><p class="Table-Head">Value</p></td>
				<td><p class="Table-Head">Description</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">0 (Default)</p></td>
				<td><p class="Table-Body">Show all modes, start in two-point 
				 mode</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">1</p></td>
				<td><p class="Table-Body">Two-point. &#160;Defines a line 
				 from two points.</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">2</p></td>
				<td><p class="Table-Body">Normal. &#160;Defines a line 
				 normal to a location on a surface.</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">3</p></td>
				<td><p class="Table-Body">Angled. &#160;Defines a line 
				 at a specified angle from a reference line.</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">4</p></td>
				<td><p class="Table-Body">Vertical. &#160;Defines a line 
				 vertical to the construction plane.</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">5</p></td>
				<td><p class="Table-Body">Four-point. &#160;Defines a line 
				 using two points to establish direction and two points 
				 to establish length.</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">6</p></td>
				<td><p class="Table-Body">Bisector. &#160;Defines a line 
				 that bisects a specified angle.</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">7</p></td>
				<td><p class="Table-Body">Perpendicular. &#160;Defines 
				 a line perpendicular to or from a curve</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">8</p></td>
				<td><p class="Table-Body">Tangent. &#160;Defines a line 
				 tangent from a curve.</p></td>
			</tr>
			<tr>
				<td><p class="Table-Body">9</p></td>
				<td><p class="Table-Body">Extension. &#160;Defines a line 
				 that extends from a curve.</p></td>
			</tr>
		</table></td>
	</tr>
	<tr style="vertical-align: top; height: 20px;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">arrPoint </p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;Array. &#160;An optional starting point. Of omitted, the 
		 user will be prompted for the starting point.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 20px;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">strMessage1 </p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;String. &#160;A prompt or message for the first point.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 20px;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">strMessage2</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;String. &#160;A prompt or message for the second point.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 20px;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">strMessage3</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;String. &#160;A prompt or message for the mid point.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 20px;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body" 
			 style="font-style: italic;">blnBothSides </p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Optional. 
		 &#160;Boolean. &#160;If <span style="font-style: italic;"><i>intMode</i></span> 
		 &gt; 0, then use this option to draw the line on both sides of 
		 the start point, creating the object twice as long as you indicate. 
		 The default value is False, or to draw the line on just one side 
		 of the start point.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 12.451%;" />
	<col style="width: 87.549%;" />
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Array</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">An 
		 array of two 3-D points that define the line if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">Null</p></td>
		<td style="padding-right: 10px; padding-left: 10px;"><p class="Table-Body">If 
		 not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim arrLine</p>
<p class="Code" style="margin-left: 12px;">arrLine = Rhino.GetLine</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrLine) Then</p>
<p class="Code" style="margin-left: 24px;">Rhino.AddLine arrLine(0), arrLine(1)</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3 class="Code">Also See</h3>
<p><a href="getbox.htm">GetBox</a></p>
<p><a href="getpoint.htm">GetPoint</a></p>
<p><a href="getpolyline.htm">GetPolyline</a></p>
<p><a href="getrectangle.htm">GetRectangle</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
