<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>AddRadialDimension</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nDimension Methods\nAddRadialDimension");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"dimension_methods.htm\">Dimension Methods<\/a> > AddRadialDimension<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>AddRadialDimension</h1>
<p>Adds a radial dimension object to the document.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.AddRadialDimension (arrPlane, arrCenter, arrArrow, 
 arrKnee [, strStyle [, blnRadius]])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.679%;" />
	<col style="width: 90.321%;" />
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrPlane</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The plane 
		 on which the dimension will lie.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrCenter</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The center 
		 point of the dimension.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrArrow</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The arrowhead 
		 point of the dimension. The distance between the center point 
		 and the arrowhead point defines the radius of the dimension.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrKnee</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;The knee point 
		 of the dimension line. The knee point is the intermediate point 
		 between the arrowhead point and the position of the text.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strStyle</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;String. &#160;The name 
		 of the dimension style. &#160;If omitted, the current dimension 
		 style is used.</p></td>
	</tr>
	<tr style="vertical-align: top; height: 24px;">
		<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnRadius</p></td>
		<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Boolean. &#160;If True 
		 (Default), a radius dimension will be created. If False, then 
		 a diameter dimension will be created.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.756%;" />
	<col style="width: 90.244%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.756%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">String</p></td>
		<td style="width: 90.244%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">The identifier of the new object if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.756%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.244%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Sub TestRadialDim</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim arrPlane, arrCenter, 
 arrPoint, arrKnee</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim arrObject, strCurve, 
 dblPoint, arrKappa, arrCrv, dblLen</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrObject = Rhino.GetObjectEx(&quot;Select 
 curve for radius dimension&quot;, 4)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsNull(arrObject) 
 Then Exit Sub</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;strCurve = arrObject(0)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If Rhino.IsLine(strCurve) 
 Then Exit Sub</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If Rhino.IsPolyline(strCurve) 
 Then Exit Sub</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrPlane = Rhino.CurvePlane(strCurve)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsNull(arrPlane) 
 Then Exit Sub</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrPoint = arrObject(3)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;dblPoint = Rhino.CurveClosestPoint(strCurve, 
 arrPoint)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrKappa = Rhino.CurveCurvature(strCurve, 
 dblPoint)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrCrv = arrKappa(4)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;dblLen = Rhino.VectorLength(arrCrv)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrCrv = Rhino.VectorUnitize(arrCrv)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrCrv = Rhino.VectorScale(arrCrv, 
 1.0 / dblLen)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrCenter = Rhino.PointAdd(arrPoint, 
 arrCrv)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrKnee = Rhino.PointSubtract(arrPoint, 
 arrCrv)</p>
<p class="Code" style="margin-left: 12px;">&#160;</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Rhino.AddRadialDimension 
 arrPlane, arrCenter, arrPoint, arrKnee</p>
<p class="Code" style="margin-left: 12px;">End Sub</p>
<h3>Also See</h3>
<p><a href="isradialdimension.htm">IsRadialDimension</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
