<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>EvaluatePlane</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nLine, Circle & Plane Methods\nEvaluatePlane");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"plane_methods.htm\">Line, Circle & Plane Methods<\/a> > EvaluatePlane<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>
<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>EvaluatePlane</h1>
<p>Evaluates a plane at a U,V parameter.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.EvaluatePlane (arrPlane, arrParameter)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.679%;" />
<col style="width: 90.321%;" />
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrPlane</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;The plane. &#160;The elements of a plane array are as follows:</p>
<table cellspacing="0" width="100%">
<col style="width: 5.146%;" />
<col style="width: 94.854%;" />
<tr valign="top">
<td style="width: 5.146%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-weight: bold;">Element</p>
</td>
<td style="width: 94.854%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-weight: bold;">Description</p>
</td>
</tr>
<tr valign="top">
<td style="width: 5.146%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">0</p>
</td>
<td style="width: 94.854%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;The plane's origin (3-D point).</p>
</td>
</tr>
<tr valign="top">
<td style="width: 5.146%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">1</p>
</td>
<td style="width: 94.854%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;The plane's X axis direction (3-D vector).</p>
</td>
</tr>
<tr valign="top">
<td style="width: 5.146%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">2</p>
</td>
<td style="width: 94.854%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;The plane's Y axis direction (3-D vector).</p>
</td>
</tr>
<tr valign="top">
<td style="width: 5.146%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">3</p>
</td>
<td style="width: 94.854%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Optional. &#160;The plane's Z axis direction (3-D vector).</p>
</td>
</tr>
</table>
</td>
</tr>
<tr style="height: 24px;" valign="top">
<td style="width: 9.679%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body" style="font-style: italic;">arrParameter</p>
</td>
<td style="width: 90.321%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Required. &#160;Array. &#160;An array containing the U,V parameter to evaluate.</p>
</td>
</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
<col style="width: 9.777%;" />
<col style="width: 90.223%;" />
<tr valign="top">
<td style="width: 9.777%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Array</p>
</td>
<td style="width: 90.223%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">The 3-D point if successful.</p>
</td>
</tr>
<tr valign="top">
<td style="width: 9.777%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">Null</p>
</td>
<td style="width: 90.223%; padding-right: 10px; padding-left: 10px;">
<p class="Table-Body">If not successful, or on error.</p>
</td>
</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim strView, arrPlane, arrPoint</p>
<p class="Code" style="margin-left: 12px;">strView = Rhino.CurrentView</p>
<p class="Code" style="margin-left: 12px;">arrPlane = Rhino.ViewCPlane(strView)</p>
<p class="Code" style="margin-left: 12px;">arrPoint = Rhino.EvaluatePlane(arrPlane, Array(5,5))</p>
<p class="Code" style="margin-left: 12px;">Rhino.AddPoint arrPoint</p>
<h3 class="Code">Also See</h3>
<p><a href="planeclosestpoint.htm">PlaneClosestPoint</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
