<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>LineBetweenCurves</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nLine, Circle & Plane Methods\nLineBetweenCurves");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"plane_methods.htm\">Line, Circle & Plane Methods<\/a> > LineBetweenCurves<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>LineBetweenCurves</h1>
<p>Finds a line segment between a pair of curves such that the line segment 
 is either tangent or perpendicular to each of the curves.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.LineBetweenCurves (strCurve0, dblParam0, blnPerp0, strCurve1, dblParam1, blnPerp1)</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 8.222%;" />
	<col style="width: 91.778%;" />
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strCurve0</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;String. &#160;The identifier 
		 of the first curve object.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblParam0</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The parameter 
		 on the first curve to be used as a seed, or starting location, 
		 of the calculation.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnPerp0</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Boolean. &#160;If True, 
		 the line perpendicular to the first curve will be calculated. 
		 Otherwise, the line tangent to the first curve will be calculated. 
		 The default is True.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strCurve1</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;String. &#160;The identifier 
		 of the second curve object.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">dblParam1</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Number. &#160;The parameter 
		 on the second curve to be used as a seed, or starting location, 
		 of the calculation.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnPerp1</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Boolean. &#160;If True, 
		 the line perpendicular to the second curve will be calculated. 
		 Otherwise, the line tangent to the second curve will be calculated. 
		 The default is True.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 8.26%;" />
	<col style="width: 91.74%;" />
	<tr style="vertical-align: top;">
		<td style="width: 8.26%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Array</p></td>
		<td style="width: 91.74%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">An array containing two 3-D points of the 
		 line segment if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.26%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 91.74%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Dim arrCurve0, arrCurve1, dblParam0, 
 dblParam1, arrLine</p>
<p class="Code" style="margin-left: 12px;">arrCurve0 = Rhino.GetObjectEx(&quot;First 
 curve&quot;, 4)</p>
<p class="Code" style="margin-left: 12px;">arrCurve1 = Rhino.GetObjectEx(&quot;Second 
 curve&quot;, 4)</p>
<p class="Code" style="margin-left: 12px;">dblParam0 = Rhino.CurveClosestPoint(arrCurve0(0), 
 arrCurve0(3))</p>
<p class="Code" style="margin-left: 12px;">dblParam1 = Rhino.CurveClosestPoint(arrCurve1(0), 
 arrCurve1(3))</p>
<p class="Code" style="margin-left: 12px;">arrLine = Rhino.LineBetweenCurves(arrCurve0(0), 
 dblParam0, true, arrCurve1(0), dblParam1, true)</p>
<p class="Code" style="margin-left: 12px;">If IsArray(arrLine) Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Rhino.AddLine arrLine(0), 
 arrLine(1)</p>
<p class="Code" style="margin-left: 12px;">End If</p>
<h3 class="Code">Also See</h3>
<p><a href="linearcintersection.htm">LineArcIntersection</a></p>
<p><a href="linecircleintersection.htm">LineCircleIntersection</a></p>
<p><a href="linecylinderintersection.htm">LineCylinderIntersection</a></p>
<p><a href="linelineintersection.htm">LineLineIntersection</a></p>
<p><a href="lineplaneintersection.htm">LinePlaneIntersection</a></p>
<p><a href="linesphereintersection.htm">LineSphereIntersection</a></p>
<p>&#160;</p>
<p>&#160;</p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
