<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="Adobe RoboHelp 8" />
<title>LineMeshIntersection</title>
<link rel="StyleSheet" href="../rhinoscript.css" type="text/css" />
<script type="text/javascript" language="JavaScript">
//<![CDATA[
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//]]>
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute;
left:0px;
top:0px;
z-index:4;
visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style>
<script type="text/javascript" language="javascript1.2" src="../whmsg.js"></script>
<script type="text/javascript" language="javascript" src="../whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whlang.js"></script>
<script type="text/javascript" language="javascript1.2" src="../whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.gbWhTopic)
{
	var strUrl = document.location.href;
	var bc = 0;
	var n = strUrl.toLowerCase().indexOf("bc-");
	if(n != -1)
	{
		document.location.href = strUrl.substring(0, n);
		bc = strUrl.substring(n+3);
	}

	if (window.setRelStartPage)
	{
	addTocInfo("RhinoScript Methods\nLine, Circle & Plane Methods\nLineMeshIntersection");
addButton("show",BTN_IMG,"Show","","","","",0,0,"../whd_show0.gif","../whd_show2.gif","../whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"../whd_hide0.gif","../whd_hide2.gif","../whd_hide1.gif");

	}

	document.write("<p style=\"text-align:right\"> ");
AddMasterBreadcrumbs("../index.html", "", ">", "Home", "../title.htm");
document.write("<a href=\"../rhinoscript_methods.htm\">RhinoScript Methods<\/a> > <a href=\"plane_methods.htm\">Line, Circle & Plane Methods<\/a> > LineMeshIntersection<\/p>");


	if (window.setRelStartPage)
	{
	setRelStartPage("../index.html");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
//]]></script>
</head>

<body><script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
//]]></script>
<h1>LineMeshIntersection</h1>
<p>Intersect an infinite line and a mesh object.</p>
<h3>Syntax</h3>
<p class="Code">Rhino.LineMeshIntersection (arrLine, strMesh [, blnReturnFaces])</p>
<h3>Parameters</h3>
<table cellspacing="0" width="100%">
	<col style="width: 8.222%;" />
	<col style="width: 91.778%;" />
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">arrLine</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;Array. &#160;Two 3-D points 
		 identifying the starting and ending points of the line.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">strMesh </p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Required. &#160;String. &#160;The identifier 
		 of the mesh object.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 8.222%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body" style="font-style: italic;">blnReturnFaces</p></td>
		<td style="width: 91.778%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Optional. &#160;Boolean. &#160;Return both 
		 intersection points and face indices. &#160;If omitted or False, 
		 then just the intersection points are returned.</p></td>
	</tr>
</table>
<h3>Returns</h3>
<table cellspacing="0" width="100%">
	<col style="width: 9.847%;" />
	<col style="width: 90.153%;" />
	<tr style="vertical-align: top;">
		<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Array</p></td>
		<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If <span style="font-style: italic;"><i>blnReturnFaces</i></span> 
		 is either omitted or False, then an array intersection points, 
		 if successful.</p></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Array</p></td>
		<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If <span style="font-style: italic;"><i>blnReturnFaces</i></span> 
		 is True, then a one-dimensional array containing information about 
		 each intersection if successful. &#160;Each array element is a 
		 one-dimensional array that contains the following two elements:</p>
		<table cellspacing="0" width="100%">
			<col style="width: 5.436%;" />
			<col style="width: 8.785%;" />
			<col style="width: 85.849%;" />
			<tr style="vertical-align: top;">
				<td style="width: 5.436%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Element</p></td>
				<td style="width: 8.785%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Type</p></td>
				<td style="width: 85.849%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body" style="font-weight: bold;">Description</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="width: 5.436%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">0</p></td>
				<td style="width: 8.785%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Array</p></td>
				<td style="width: 85.849%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">The 3-D intersection point.</p></td>
			</tr>
			<tr style="vertical-align: top;">
				<td style="width: 5.436%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">1</p></td>
				<td style="width: 8.785%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">Number</p></td>
				<td style="width: 85.849%; padding-right: 10px; padding-left: 10px;"><p 
					 class="Table-Body">The mesh face index on which the 
				 intersection point lies.</p></td>
			</tr>
		</table></td>
	</tr>
	<tr style="vertical-align: top;">
		<td style="width: 9.847%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">Null</p></td>
		<td style="width: 90.153%; padding-right: 10px; padding-left: 10px;"><p 
			 class="Table-Body">If not successful, or on error.</p></td>
	</tr>
</table>
<h3>Example</h3>
<p class="Code" style="margin-left: 12px;">Sub TestLineMeshIntersection</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;Dim strMesh, arrStart, 
 arrEnd, arrLMX, arrPt</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;strMesh = Rhino.GetObject(&quot;Select 
 mesh&quot;, 32)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsNull(strMesh) 
 Then Exit Sub</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrStart = Rhino.GetPoint(&quot;Start 
 of line&quot;)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsNull(arrStart) 
 Then Exit Sub</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrEnd = Rhino.GetPoint(&quot;End 
 of line&quot;, arrStart)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsNull(arrEnd) 
 Then Exit Sub</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;arrLMX = Rhino.LineMeshIntersection(Array(arrStart, 
 arrEnd), strMesh, False)</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;If IsArray(arrLMX) 
 Then</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;For 
 Each arrPt in arrLMX</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;&#160;&#160;Rhino.AddPoint 
 arrPt</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;&#160;&#160;Next</p>
<p class="Code" style="margin-left: 12px;">&#160;&#160;End If</p>
<p class="Code" style="margin-left: 12px;">End Sub</p>
<h3>Also See</h3>
<p><a href="linearcintersection.htm">LineArcIntersection</a></p>
<p><a href="lineboxintersection.htm">LineBoxIntersection</a></p>
<p><a href="linecircleintersection.htm">LineCircleIntersection</a></p>
<p><a href="linecurveintersection.htm">LineCurveIntersection</a></p>
<p><a href="linecylinderintersection.htm">LineCylinderIntersection</a></p>
<p><a href="linelineintersection.htm">LineLineIntersection</a></p>
<p><a href="lineplaneintersection.htm">LinePlaneIntersection</a></p>
<p><a href="linesphereintersection.htm">LineSphereIntersection</a></p>
<script type="text/javascript" language="javascript1.2">//<![CDATA[
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);

highlightSearch();
//-->
//]]></script>
</body>
</html>
